fireice-uk/xmr-stak

- xmrstak/backend/amd/autoAdjust.hpp
Platform index zero was always used to search for the device detection.
Fix: use correct detected AMD platform index
Fix bug detected from @anhphan https://github.com/fireice-uk/xmr-stak/issues/5#issuecomment-334225424
> fix amd auto suggestion

- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
The number of threads within a kernel must be a multiple of the worksize.
If not it can crash on some systems.
fix #1
> fix invalid kernel call parameter

- xmrstak/misc/executor.cpp
fix #21, hash values randomly not available.
The reason is that I changed the lables but forget to change all timer.
A GPU needs sometimes ore than 2.5s to finish one hash round, therefore
the results are only visible randomly.
> fix wrong timer for stats

- .travis.yml
fix broken travis OSX build
```
/usr/local/Homebrew/Library/Homebrew/brew.rb:12:in `<main>': Homebrew must be run under Ruby 2.3! (RuntimeError)
```
> fix travis OSX build

- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
Is is possible that the number of results are greater than the result output array, in this case invalid memory can be access within the device and on the host side.
The possibility of this bug should be very small, but statistics can be a beast :bear:
> avoid possible illegal memory access

- CMakeLists.txt
fix #3
- remove QUIET from find package for OpenCL and CUDA
- remove pascal architecture from default CUDA_ARCH for CUDA < 8.0
- remove sm_20 for CUDA >= 9.0
> fix CMake find package output

- CMakeLists.txt
fix #34
fix error: `identifier "__builtin_ia32_monitorx" is undefined`
> fix cuda 7.5 compile

- xmrstak/misc/environment.hpp
> Keep consistency between class and struct

- xmrstak/backend/amd/minethd.cpp
- xmrstak/backend/nvidia/minethd.cpp
- xmrstak/misc/environment.hpp
This change makes sure of two things:
- Singleton ptr is always null at first
- We have only single env instance, so we don't duplicate singletons if we create them after the dll is loaded
Not testes at all, but should work. Let me know if there are any problems
> Make sure all singletons are set to null and make env a global ptr

- CMakeLists.txt
- doc/compile.md
- xmrstak/cli/cli-miner.cpp
Thanks for help @anhphan This version includes a UAC manifest by default, since Windows 7 insists on running elevated to lock large pages.
> Re-add UAC manifest and WIN_UAC cmake option

- xmrstak/backend/cpu/minethd.cpp
This fixes a freeze when a double thread is present.
> add order_fix for double hash

- xmrstak/backend/amd/amd_gpu/gpu.cpp
fix bug announced in #52 [post](https://github.com/fireice-uk/xmr-stak/issues/52#issuecomment-337854623)
If the miner is compiled in debug mode the assert condition results in a compile time error.
The bug was introduced with #16
> fix assert in AMD backend

- xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
use `__shffl_snyc` if CUDA 9+ is avalable
warning:
```
xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_core.cu(159): warning: function "__shfl(int, int, int)"
cuda_9_0/include/sm_30_intrinsics.hpp(152): here was declared deprecated ("__shfl() is not valid on compute_70 and above, and should be replaced with __shfl_sync().To continue using __shfl(), specify virtual architecture compute_60 when targeting sm_70 and above, for example, using the pair of compiler options: -arch=compute_60 -code=sm_70.")
```
> fix CUDA 9 shuffle warning

- xmrstak/backend/nvidia/nvcc_code/cuda_blake.hpp
- remove restricted pointer
- change some sizes to `unit32_t` to avoidwrong compiler optimization
The blake algorithm code is equal to the host code implementation but the developer added to all pointer parameter the `restrict` keyword. The usage of restrict can have negative effect because the compiler is free to do many code optimizations. This can result in errors. I identified the broken line and checked why the illegal memory access was triggered. I can't find any bug expected the `restrict` keyword.
By changing some array sizes to `uint32_t` another error can be removed. It could be that this is an compiler bug (this is not the first time that some `int` optimizations created wrong code).
The bug is not triggered on all gpus (I got it with sm_70).
This PR solves closed many issues …
> fix illegal memory access

- CMakeLists.txt
fix #56
Search for AMD OpenCL inlcude path and libaries to prioritize the AMD implementation over NVIDIA and Intel.
If still NVIDIA OpenCL is found it could be necessary to set the environment variable `OpenCL_ROOT` to the installation path of the AMD app SDK.
> prefere AMD OpenCL over NVIDIA, Intel

- xmrstak/backend/cpu/minethd.cpp
- remove double copied memory
The copy is moved to method `prep_double_work` in PR #19
> remove double blob copy

- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/amd_gpu/gpu.hpp
- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
- xmrstak/backend/amd/minethd.cpp
- xmrstak/backend/miner_work.hpp
- xmrstak/misc/executor.cpp
- xmrstak/net/jpsock.cpp
- xmrstak/net/msgstruct.hpp
- remove 32bit target value
- use always 64bit target for amd backend
\* can someone please test this changes
> amd: use 64bit target

- xmrstak/backend/amd/minethd.cpp
- xmrstak/backend/amd/minethd.hpp
- xmrstak/backend/cpu/minethd.cpp
- xmrstak/backend/nvidia/minethd.cpp
- xmrstak/backend/nvidia/minethd.hpp
This is a follow up of #43 and use the some mechanism to set the thread affinity for
non cpu backends correct.
- use cpu affinity workflow for nvidia and amd
- amd/nvidia: bind host memory with numaloc if affinity is given
- cpu: move messages of thread spawning before thread creation
> thread affinity for non cpu backends

- xmrstak/backend/amd/autoAdjust.hpp
- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
- increase safty memory from 64 to 128 MiB
- NVIDIA: increase lmem reserve per thread to 1kiB
This should avoid that the autosuggestion create a config which use to much memory.
> increase safety memory for autosuggestion

- .appveyor.yml
- xmrstak/backend/cpu/hwlocMemory.cpp
- xmrstak/backend/cpu/hwlocMemory.hpp
- xmrstak/backend/nvidia/minethd.cpp
- xmrstak/backend/nvidia/minethd.hpp
- xmrstak/backend/nvidia/nvcc_code/cryptonight.hpp
- xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
This PR tests CUDA and OpenCL under Windows.
- install CUDA
- compile miner with CUDA and OpenCL
- compile without UAC
- switch from VS 2017 to VS 2015
For the CI we switched from VS 2017 to 2015 else CUDA8 will not install on the command line. I am not sure if this has changed with CUDA9. This can be investigated later.
> appveyor CUDA support

- xmrstak/backend/cpu/hwlocMemory.cpp
- xmrstak/backend/cpu/hwlocMemory.hpp
- xmrstak/backend/nvidia/minethd.cpp
- xmrstak/backend/nvidia/minethd.hpp
- xmrstak/backend/nvidia/nvcc_code/cryptonight.hpp
- xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
- fix windows linker error during compile #75
- create file `hwlocMemory.cpp`
- fix wrong parameter to call aeon (nvidia-backend)
- move compile time specialization to CUDA code file
After fixing #75 there was a second compile issue in the nvidia-backend. 
I realized that the nvidia aeon and xmr support in the current dev is broken. I used the wrong order for two template arguments and used the monero parameter for aeon. I don't know how I passed my tests (maybe dirty environment)
I repeated the tests for aeon and monero on a clean environment.
> fix windows compile and broken aeon

- xmrstak/config.tpl
- xmrstak/jconf.cpp
- xmrstak/misc/console.cpp
- xmrstak/misc/console.hpp
Added the option to forcefully flush STDOUT, which may be useful when running the miner through a pipe instead than a shell.
If STDOUT is a shell, it's unbuffered by default.
If STDOUT is a pipe, it's buffered by default.
This PR is ported from https://github.com/fireice-uk/xmr-stak-cpu/pull/352 to the new miner base.
> add option: flush stdout

- xmrstak/backend/amd/autoAdjust.hpp
- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
- allow to use up to 2024 threads on VEGA gpus
fix #5
> tune VEGA auto suggestion

- CMakeLists.txt
fix #71 
- link `xmr-stak-backend` to `xmrstak_cuda_backend` to solve missing symbols
Before this PR the symboles of `console.hpp, ...` was linked only on windows to CUDA  and OpenCL. This can result in missing symbols.
> fix OSX compile

- xmrstak/backend/plugin.hpp
fix #71 (can't find back-end library)
This is a follow up of #84.
- use `.dylib` as dynamic library file extension
> OSX file file extension (dynamic libraries)

- xmrstak/backend/nvidia/autoAdjust.hpp
- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
- avoid creation of a config with zero threads or blocks
- WINDOWS: reduce the used memory for the auto suggestion by the amount of already used memory
We use in windows bfactor (split slow kernel into smaller parts) to avoid that windows is killing long running kernel.
In the case there is already memory used on the gpu than we assume that other application are running between the split kernel, this can result into TLB memory flushes and can strongly reduce the performance and the result can be that windows is killing the miner.
Be reducing maximum memory for the autosuggestion be the amount of the current used memory we try to avoid this effect.
This PR is related to #88
> optimize NVIDIA autosuggestion

- CMakeLists.txt
- doc/compile_Windows.md
fix #91
- add CMake workaround for wrong host compiler for cuda
- update winows compile documentation
I tested the compile with CUDA 9 under windows 10 with VS Community 2017.
> fix windows CUDA 9 compile

- xmrstak/misc/executor.cpp
Linux will terminate an network application randomly unless this is disabled. Not a large issue on the miner (on the pool it only became a problem over 1000 connections per minute), but can happen.
> Disable sigpipe on posix systems

- xmrstak/backend/amd/minethd.cpp
- xmrstak/backend/cpu/minethd.cpp
- xmrstak/backend/iBackend.hpp
- xmrstak/backend/nvidia/minethd.cpp
- xmrstak/misc/executor.cpp
close #8
- add type of the backend to each backend-plugin
- add `gteName` to `iBackend` to get the name of the backend
- report hash rate per backend
- split hash report for web interface and the json
- add total hash rate per backend
```
HASHRATE REPORT - CPU
| ID | 10s |  60s |  15m | ID | 10s |  60s |  15m |
|  0 | 65.0 | 64.9 | (na) |  1 | 40.3 | 40.1 | (na) |
|  2 | 40.4 | 40.1 | (na) |  3 | 41.6 | 41.4 | (na) |
|  4 | 65.5 | 65.2 | (na) |  5 | 40.6 | 40.5 | (na) |
|  6 | 40.6 | 40.6 | (na) |  7 | 41.7 | 41.5 | (na) |
-----------------------------------------------------
HASHRATE REPORT - NVIDIA
| ID | 10s |  60s |  15m | ID | 10s |  60s |  15m |
|  0 | 39.1 | 39.3 | (na) |  1 | 39.6 | 39.9 | (na) |
|  2 | 37.6 | 37.2 | (na) |  3 | 39.8 | 39.5 | (na) | …
```
> improve cli hash report

- xmrstak/backend/amd/minethd.cpp
- xmrstak/backend/amd/minethd.hpp
- xmrstak/backend/cpu/minethd.cpp
- xmrstak/backend/cpu/minethd.hpp
- xmrstak/backend/nvidia/minethd.cpp
- xmrstak/backend/nvidia/minethd.hpp
- xmrstak/cli/cli-miner.cpp
- xmrstak/jconf.cpp
- xmrstak/misc/executor.cpp
- xmrstak/misc/executor.hpp
- xmrstak/net/msgstruct.hpp
Three issues 
- CONF_NO_TLS option wasn't handled properly
- log_result_error has been made public, which resulted in a threading violation
- DeadToo's idea of returning to scheduler after a pin but before mem allocation.
> Fix misc bugs

- xmrstak/backend/nvidia/autoAdjust.hpp
- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
Free and total memory is only evaluated on the first device.
To detect the gpu memory the gpu must be selected.
- create context on the gpu before the memory is checked
- add smx to the auto detection
- change the result code of `cuda_get_deviceinfo()`
This bug is also included in the xmr-stak-nvidia repository.
> fix wrong memory detection

- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
The lmem is still incalculably and crash the miner very often.
Increase the potential lmem usage to 16kiB to respect lmem alignments, ...
> fix nvidia auto suggestion

- xmrstak/misc/executor.cpp
- xmrstak/net/msgstruct.hpp
Fairly trivial issue - forgot to add copy code so the application tried to read random memory.
I added an explicit constructor too, just to make it clearer what is happening.
> Fix GPU result crash

- xmrstak/backend/amd/amd_gpu/gpu.cpp
- handle opencl errors to avoid unexpected behaviors
- remove code duplicatio nwithin the some method
Handle the most important OpenCL API calls to avoid that e.g. the device list is created if the API call to get the number of devices is failing.
This can maybe help to analyse #129
> handle OpenCL errors

- xmrstak/backend/amd/amd_gpu/gpu.cpp
The max work size shown to the user was the hardware maximum but not take in account thet some kernel spwning 8 times more threads per work group than configured by the user.
> fix max work size shown to user

- CMakeLists.txt
This will fix linker issues I had on two different Windows systems.
add microhttpd libs explicit to `xmr-stak-c`
> fix broken windows compile with v140

- doc/compile_Windows.md
Point to new xmr-stak-dep precompiled binaries if CUDA9 is used.
> update windoes compile guide

- .appveyor.yml
Remove the execution of the binary at the end of the CI test. This is only currently a temporary solution.
The windows CI is broken since #143
> fix appvoyer

- xmrstak/misc/executor.cpp
Uninitialized memory access is UB in C/C++, fix it.
> Fix uninitialized memory accces

- xmrstak/misc/executor.cpp
> Fix indent on hash rate report.

- .appveyor.yml
- doc/compile_Windows.md
Add explicit note that VSC v141 should be used for AMD and CPU compile only.
fix #153
> update windows compile guide  

- xmrstak/backend/amd/amd_gpu/gpu.cpp
Fix for AMD GPU detection on MacOS X
On MacOS X the platform is reported as Apple, and the vendor is reported as AMD.
**Output from existing code on MacOS X with AMD GPU**
[2017-11-21 12:55:03] : Start mining: MONERO
[2017-11-21 12:55:03] : WARNING: No AMD OpenCL platform found. Possible driver issues or wrong vendor driver.
[2017-11-21 12:55:03] : WARNING: backend AMD disabled.
**Output from code with fix**
[2017-11-21 12:56:56] : Start mining: MONERO
[2017-11-21 12:56:56] : Found AMD platform index id = 0, name = Apple
[2017-11-21 12:56:56] : Found OpenCL GPU AMD Radeon Pro 455 Compute Engine.
[2017-11-21 12:56:56] : AMD: GPU configuration stored in file 'amd.txt'
[2017-11-21 12:56:56] : Compiling code and initializing GPUs. This will take a while...
[2017-11-21 12:56:56] : WARNING: …
> Fix for AMD GPU detection on MacOS X

- doc/compile.md
- doc/compile_MacOS.md
- doc/usage.md
This PR is a repost of #169 with some modifications to address @psychocrypt review.
It adds compilation instructions (including dependencies installation instructions) for MacOS for either Nvidia GPUs or CPU-only mining.
> Add compilation instructions for MacOS

- .appveyor.yml
- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
Increase bfactor for all devices with lesser than 6 multi processors.
This PR should fix #172.
> fix auto suggestion for low end devices 

- xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
fix #191
lauch bounds must be placed before the return type but after the template paramater
> fix CUDA launch bounds usage

- CMakeLists.txt
- fix wrong compare for HWLOC not found
- remove usage of microhttpd variable if microhttpd is disabled
- remove all `"${VARNAME}` usages in if conditions
- increase cmake minimum version to 3.1 to have the new behavior of [CMP0054](https://cmake.org/cmake/help/v3.1/policy/CMP0054.html)
> fix CMake 

- doc/compile_Windows.md
add hint that the new compiled xmr-stak-dep must be used for the new VS tool chain
> update windows build documentation

- doc/usage.md
- xmrstak/cli/cli-miner.cpp
- xmrstak/misc/console.cpp
- add documentation
- add environment variable `XMRSTAK_NOWAIT` to disable the dialog `Press any key` on windows.
After this PR and #305 is merged we can activate the appvoyer binary test again if we set the environment variable.
> add environment variable `XMRSTAK_NOWIT`

- doc/tuning.md
- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/amd_gpu/gpu.hpp
- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
- xmrstak/backend/amd/autoAdjust.hpp
- xmrstak/backend/amd/config.tpl
- xmrstak/backend/amd/jconf.cpp
- xmrstak/backend/amd/jconf.hpp
- xmrstak/backend/amd/minethd.cpp
Allow to change the indexing used to address the hash scratchpad memory.
- add option `strided_index` for each gpu
I changed the indexing in the old amd version https://github.com/fireice-uk/xmr-stak-amd/pull/35. Some users reported a hash rate decrease. This option will give the user the opportunity to tune the indexing depending of the hardware. ~~The default is equal to the current dev.~~ 
The default option will be `true` which gives a few hashes more on newer hardware. I changes it in the past based on my results of a HD7870.
> add AMD scratchpad indexing option

- xmrstak/backend/amd/amd_gpu/opencl/wolf-aes.cl
Unroll AES round by hand to help the compiler to optimize the command queue.
This pull request will should improve the hash rate by a few hashes.
> optimize aes round command queue

- xmrstak/misc/executor.cpp
I wanted to make the hashrate report columns line up.  This is the result.  Should allow for a hashrate up to 9999.9.
> Right align hashrate report to six characters

- xmrstak/cli/cli-miner.cpp
- xmrstak/misc/executor.cpp
- xmrstak/net/jpsock.hpp
fix #340
With #90 the option to overwrite the pool settings via CLI options is broken.
This pull request will allow to overwrite the options of the pool with the highest weighting.
> fix broken pool option overwrite via CLI

- xmrstak/backend/nvidia/autoAdjust.hpp
- xmrstak/backend/nvidia/config.tpl
- xmrstak/backend/nvidia/jconf.cpp
- xmrstak/backend/nvidia/jconf.hpp
- xmrstak/backend/nvidia/minethd.cpp
- xmrstak/backend/nvidia/nvcc_code/cryptonight.hpp
- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
- add option `sync_mode`
- update auto suggestion and jconf
Setting `sync_mode` to `2` can increase the gpu hash rate by up to `4%` but will create some load on one thread per gpu. The default will be the same then before.
> option to controll gpu synchronization

- .appveyor.yml
- CMakeLists.txt
- doc/compile.md
- doc/tuning.md
- doc/usage.md
- xmrstak/cli/cli-miner.cpp
- remove CMake option `WIN_UAC`
- spawn UAC dialog via restarting xmr-miner with administrator right
- allow to disable UAC with `--noUAC`
- update documentation
- remove usage section with help message (output depends on OS)
> allow to diable UAC dialog

- xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
- xmrstak/backend/nvidia/nvcc_code/cuda_device.hpp
- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
- add macro `CUDA_CHECK_MSG_KERNEL` and `CUDA_CHECK_MSG`
- add suggestion how typical errors can be solved
example:
```
[CUDA] Error gpu 0: </home/widera/workspace/xmr-stak-nvidia/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:218
**suggestion: Try to reduce the value of the attribute 'threads' in the NVIDIA config file.**
terminate called after throwing an instance of 'std::runtime_error'
what():  [CUDA] Error: out of memory
Aborted
```
> add message to `CUDA_CHECK...` macros

- CMakeLists.txt
change `MICROHTTPD_ROOT` to `HWLOC_ROOT` within the hwlock section
thx @maztheman for spotting the bug
> CMake: fix wrong variable name

- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
Be more conservative with the auto suggestion.
- increase bfactor if `smx <= 6`
- limit memory for pascal < GTX1070 to 2GiB
- limt memory for pascal <= GTX1080 to 4GiB
This PR should avoid many errors and for the GTX1080 the auto suggestion hash rate will be increased a little bit (tested on linux).
> conservative NVIDIA auto suggestion

- xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
When compiled with VS2017, the negative applied to the uint wait time is ignored. Fixed by casting first.
This has vastly improved stability on my Windows 10 setup and has increased performance significantly.
> Fix compat_usleep for WIN32

- xmrstak/misc/console.cpp
Honor the config file's flush_stdout setting when printing reports.
> Also fflush in printer::print_str() if configured to do so

- CMakeLists.txt
- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
- fix cuda9.1 compile (remove include of device_functions.hpp/ removed with cuda9.1)
- remove NVIDIA Volta gpus for MAC OSX (https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-general-known-issues)
should solve #473 #492 #530 #287
> fix cuda9.1 compile

- CMakeLists.txt
fix compile on windows together with #532 
fix #523 and #534
apply cmake patch for CUDA 9.0 also for CUDA 9.1
> fix windows compile with CUDA 9.1

- CMakeLists.txt
fix #646
remove adding compiler flags `-static-...` if compiler is not a gnu compiler
> fix static compile with non gnu compiler

- xmrstak/version.cpp
Increase version for a bug fix release. ~~Because of the reason we have only fixed bugs I increased only the bug fix number in the version.~~
update: @taisel released a xmr-stak version https://www.reddit.com/r/MoneroMining/comments/7lfj4d/updated_the_xmrstak_fork/?ref=share&ref_source=link under a version number which conflicts with our versioning order. For the user it looks like the fork is newer than our next release. This is not the case therefore we need to increase the second number instead the third.
> increase version to 2.2.0

- xmrstak/backend/amd/minethd.cpp
- xmrstak/backend/nvidia/minethd.cpp
- xmrstak/misc/executor.cpp
- xmrstak/net/msgstruct.hpp
I was unable to tell which GPU was creating invalid hashes. This modification of the error report fixes that.
> Modify invalid result report to show GPU id

- xmrstak/backend/cpu/crypto/cryptonight_aesni.h
I moved the two prefetch commands to take place as early as possible to give the cache time to fetch from slow memory. On my mediocre CPU (i7-3770S) this increases the hash rate by about 1%. The effect is probably more noticable for CPUs with small cache.
Before this patch 277.7 H/s, afterwards 280.8 H/s
This is a resubmission of #670 which I messed up.
> Rearrange prefetch for slight performance increase in CPU miner

- doc/Linux_deployment.md
it's not installed in ubuntu by default.
> install curl first

- README.md
- doc/compile.md
- doc/compile_macOS.md
- doc/usage.md
- xmrstak/backend/amd/minethd.cpp
- xmrstak/backend/cpu/minethd.cpp
- xmrstak/backend/nvidia/minethd.cpp
Apple has a silly way of capitalizing things, but it's still part of the name.
Basically this pull request is just `s/MacOS/macOS/g`
> Rename "MacOS" to "macOS"

- xmrstak/misc/executor.hpp
Fixes bug reported in #607 
To test, simply run and observe difficulty and pool-side hashes. Pool-side hashes should increase by difficulty every time the miner submits a result.
> Fix bug in pool-side hashes

- xmrstak/backend/cpu/autoAdjust.hpp
bug was introduced with #67
- increase the L3 sanity check to 2GiB
- fix usage of byte instead of KB
> fix autosuggestion CPU

- doc/compile_Linux.md
Only install if the user doesnt already have the packages installed, no
point in reinstalling everything.
> Add --needed to pacman install

- xmrstak/backend/cpu/minethd.cpp
Ignore any affinity >=64 and throw a warning.
> fix set affinity for windows

- xmrstak/misc/executor.cpp
As in #125 suggested each mining component (CPU, GPU) now displays an individual sum in the hashrate report. I also changed this display of sums to show "0.0" instead of "(na)" if one of the summed up components shows (na)
> #125: separate hashrate sums for each component

- doc/compile_Windows.md
Fix for #750, #626, #606, #534, without having to downgrade and do not require modification of host_config.h
Require an additional component during VS2017 installation (VC++ 2017 version 15.4 v14.11 toolset) and an additional command execution before compilation.
> Fix for compiling with Cuda 9.1 on VS 2017 version >= 15.5

- xmrstak/backend/amd/amd_gpu/opencl/wolf-skein.cl
- Eliminate modulus math (It runs slow inside microcode).
- Convert whatever the hell was going on into a rotate op. Like... Someone kinda reinvented the wheel in order to do a simple rotate.
> Optimize Skein

- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
reduce memory usage to 1GiB for NVIDIA devices with <=6 SMX
This PR should solve many issue we will have with low end NVIDIA GPUs. The GPUs are not able to compute enough hashes within 10 sec.
> reduce memory usage for low end gpus

- xmrstak/backend/amd/autoAdjust.hpp
Occassionally the auto adjust doesn't find enough memory and the
intensity is detected too low and aligned to 0 with the compute units.
This patch fixes this situation by issuing a warning with a suggestion
to set environment vars and then ignoring the alignment to 0
Per several issues:
Principally:
https://github.com/fireice-uk/xmr-stak/issues/81
Related:
https://github.com/fireice-uk/xmr-stak/issues/490
https://github.com/fireice-uk/xmr-stak/issues/472
> Add warning and fallback when auto intensity is 0

- xmrstak/backend/cpu/minethd.cpp
follow up of #978
The cpu miner backend uses the wrong ranges of nonces instead of using `[startNonce,startNonce + nonce_chunk)`
(startNonce,startNonce + nonce_chunk]` is used. This will results in an overlap with nonces used by the gpu back-ends.
I used the [mathematics interval](https://en.wikipedia.org/wiki/Interval_(mathematics)) notation to to describe valid nonces which can be used based on the `start_none` from [here](https://github.com/fireice-uk/xmr-stak/blob/2ae7260b90fe3dbe835ba2489519510f0e57d770/xmrstak/backend/cpu/minethd.cpp#L437) .
e.g. if the `result.iNonce` is `20` and `nonce_chunk` is 4 than `[20,24)` are allowed nonces.
In line [440](https://github.com/fireice-uk/xmr-stak/blob/2ae7260b90fe3dbe835ba2489519510f0e57d770/xmrstak/backend/cpu/minethd.cpp#L440) …
> avoid nonce overlapping

- xmrstak/backend/amd/jconf.cpp
The AMD jconf.cpp would only accept an array. The config sample, and the nvidia and cpu config work with the value 'null', as they accept a 'kNullType'. This means at current, AMD GPUs could not be turned off, the config file wouldn't parse on load.
This change makes AMD consistent with the others, and can now be disabled.
> Fix Disabling AMD GPUs

- xmrstak/backend/amd/amd_gpu/gpu.cpp
fix that the GPU name is printed before the name is queried from OpenCL
> fix output of gpu name

- xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
- enable L1 cache for Nvidia Volta GPUs and newer
- remove explicit cache controll for Volta GPU and newer
This pull request increases the hash rate for Volta GPUs by ~5%
> speedup Volta

- .travis.yml
Currently the CI fails due to the issue
```
Error: homebrew/science was deprecated. This tap is now empty as all its formulae were migrated.
The command "if [ $TRAVIS_OS_NAME = osx ]; then brew update; brew tap homebrew/science; fi" failed and exited with 1 during .
```
Until the fix is implemented the OSX tests will be disabled.
> disable OSX CI tests

- xmrstak/cli/cli-miner.cpp
Some messages from the start of the miner are not printed to the log file. The reason is that the log file is initialized to late. For hash rate monitors it is important to detect the last start in the log files. 
Thx @JerichoJones for reporting of this issue.
- initialize the log file as fast as possible after the start of the miner
> fix missing message in log file

- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
reduce usage of registers: based on the suggestion of @enerc77 [patch](https://github.com/fireice-uk/xmr-stak/issues/300#issuecomment-364755190)
> AMD: reduce register usage

- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/amd_gpu/gpu.hpp
- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
- xmrstak/backend/amd/autoAdjust.hpp
- xmrstak/backend/amd/config.tpl
- xmrstak/backend/amd/jconf.cpp
- xmrstak/backend/amd/jconf.hpp
- xmrstak/backend/amd/minethd.cpp
Allow to fine tune the memory pattern of the scratchpad memory. Different AMD architectures can benefit from chunked memory blocks. Special layouts can reduce the memory load conflicts.
This PR changing not the old default but give the user the option to fine tune the device.
- add new option for `strided_index`
- add additional option if `strided_index == 2` to controll the memory chunk with
direct download: https://github.com/psychocrypt/xmr-stak/archive/topic-blockedStride3.zip
- compile the PR
- remove your `amd.txt`
- start the miner
- edit `amd.txt` and add your old intensity and double threads per device if needed
- test the hash rate
- tweak `mem_chunk` (values between 0 and 18 are allowed)
> AMD: option `mem_chunk`and new `strided_index`

- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/amd_gpu/gpu.hpp
- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
- xmrstak/backend/amd/autoAdjust.hpp
- xmrstak/backend/amd/config.tpl
- xmrstak/backend/amd/jconf.cpp
- xmrstak/backend/amd/jconf.hpp
- xmrstak/backend/amd/minethd.cpp
- add new option `comp_mode` to the amd config
- disable if guards within opencl kernel if `comp_mode : false`
Many users report that the hash rate with the amd miner before the unified version was better than now. This PR will allow to remove the in kernel guards which allows to call a kernel with a intensity which is not a multiple of the worksize. Maybe the ifs in the kernel prevent the compile to optimize a few lines of code. This PR should show if there is a improve available without the if guards.
- compile the miner
- remove/rename your old amd.txt
- start the miner (a new amd.txt is created)
- check the hash rate (must be equal to the current release)
- change `comp_mode` in amd.txt to false (hope that the `intensity` is a multiple of the `worksize`)
- run the miner and compare …
> add OpenCL compatibility mode

- xmrstak/backend/amd/amd_gpu/gpu.cpp
guard error types those are only defined in OpenCL >1.1
A few community members ask for OpenCl 1.1 support to mine with there very old devices.
> fix compile with OpenCL 1.1

- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
- xmrstak/backend/amd/autoAdjust.hpp
- xmrstak/backend/amd/config.tpl
- fix double definition of define `MEM_CHUNK`
- change the default value for `mem_chunk`
Bug was introduced with #1087.
Download: https://github.com/psychocrypt/xmr-stak/archive/fix-memChunk.zip
> fix broken memchunk feature

- THIRD-PARTY-LICENSES
- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/picosha2/picosha2.hpp
Reduce OpenCL start time by using a self made compiler cache.
- store compiled OpenCL binary
- load OpenCl binary if available
- add project picosha2
solve: #1018
- the compiled binary is stored into a file during the first start
- if the code and compile parameter not change the binary is loaded with the second start of the miner
ignore white spaces during the code review [direct link to the diff without white space changes](https://github.com/fireice-uk/xmr-stak/pull/1131/files?w=1)
> OpenCL compile cache

- xmrstak/backend/nvidia/minethd.cpp
- xmrstak/backend/nvidia/minethd.hpp
This PR reduces the startup for NVIDIA multi GPU systems. e.g 8 GPUs startup from over 1 minute to a few seconds. 
- reduce startup time for multi gpu systems
- initialize the GPU memory non concurrent
- 1. start thread (done by master process)
- 2. numa bind CPU memory (done by thread)
- 3. allocate GPU memory (done by thread)
- 4. repeat 1-3 for all GPU threads
- 5. set thread affinity (done by process)
> CUDA: reduce startup time

- xmrstak/backend/amd/amd_gpu/gpu.cpp
A redefinition of a variable in a local scope avoid that the intensity is rounded to a multiple of the work size.
This bug was introduced with #613 and solves #1155.
> fix shadowed variable

- xmrstak/cli/cli-miner.cpp
The OpenCl code is only supporting jobs up to 84byte
> fixAMD benchmark mode

- .travis.yml
- remove `brew trap science`
MACOSX travis tests was removed with #1066 to pass the CI.
> reenable MACOSX travis tests

- .travis.yml
- xmrstak/backend/cpu/autoAdjust.hpp
fix #1214, fix #1210
- remove call `IsCurrencyMonero` with `cn_select_memory`
- travis: more compile combinations 
- add tests whith disabled dependencies
> fix autoAdjust(non hwloc)

- doc/usage.md
add note that `rig_id` is ignored by some pools
inspirit by #1230
> documentation: name a worker

- xmrstak/backend/amd/amd_gpu/gpu.cpp
fix warning
```
/Users/user/xmr-stak/xmrstak/backend/amd/amd_gpu/gpu.cpp:481:11: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
if( ret = clGetProgramInfo(ctx->Program, CL_PROGRAM_BINARIES, num_devices * sizeof(char*), all_programs.data(),NULL) != CL_SUCCESS)
```
> fix parentheses warning

- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/cli/cli-miner.cpp
- xmrstak/params.hpp
allow to disable the OpenCl cache
- useful for read only systems
- useful for unknown errors during cache reading
can be used as workaround for #1225
> add cli option `--noAMDCache`

- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
fix #1218
- remove inline function with ugly macro :-(
OSX not allows the memory qualifier `__local`. It is not clear if this is not allowed in all OSX OpenCL versions or only in some. Therefore the ugly macro is currently the best solution.
> fix OpenCl AMD on OSX

- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
fix #1297
If sm_20 is mixed with other architectures the detection for the minimal supported architecture is broken.
> fix cuda architecture detection

- xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
- xmrstak/version.cpp
fix #1295
sumokoin is broken if `bfactor >= 5` is used (default for windows)
sumokoin for `sm_20` is broken due to the missing extern shared memory
- call phase3 kernel two times if sumokoin is enabled
- create extern shared memory for phase3 kernel
> NVIDIA: fix sumokoin

- xmrstak/backend/amd/autoAdjust.hpp
- xmrstak/backend/backendConnector.cpp
- xmrstak/backend/backendConnector.hpp
- xmrstak/backend/cpu/autoAdjust.hpp
- xmrstak/backend/cpu/autoAdjustHwloc.hpp
- xmrstak/backend/cpu/crypto/skein_port.h
- xmrstak/backend/cpu/jconf.cpp
- xmrstak/backend/cpu/jconf.hpp
- xmrstak/backend/cpu/minethd.cpp
- xmrstak/backend/cpu/minethd.hpp
- xmrstak/backend/globalStates.cpp
- xmrstak/backend/globalStates.hpp
- xmrstak/backend/iBackend.hpp
- xmrstak/backend/miner_work.hpp
- xmrstak/backend/nvidia/autoAdjust.hpp
- xmrstak/backend/nvidia/jconf.hpp
- xmrstak/backend/nvidia/minethd.hpp
- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
- xmrstak/backend/plugin.hpp
- xmrstak/misc/configEditor.hpp
- xmrstak/misc/environment.hpp
- xmrstak/misc/executor.hpp
- xmrstak/misc/telemetry.cpp
- xmrstak/misc/telemetry.hpp
- xmrstak/misc/utility.cpp
- xmrstak/misc/utility.hpp
- xmrstak/net/msgstruct.hpp
- xmrstak/params.hpp
NITPICK: Typos in comments only, changes no actual code
> Repair all 'namepsace' to 'namespace' (all within comments)

- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/amd_gpu/gpu.hpp
- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
- xmrstak/backend/amd/minethd.cpp
- remove version numbers within the kernel
- create seperate program context for each mining algorithm
- remove kernel `cn1_monero` is now integrated in `cn1`
- remname `cnX` kernel in `cnX + algorithmNumber`
This PR fixes `haven` support, before the amd code was hard forking on version 3 to cryptonight-heavy.
> amd simplify kernel for different algorithms

- doc/FAQ.md
The link to the `why monero7` FAQ was dead because it tried to go to a new page. Documentation only, no code changes.
> Fix FAQ link

- xmrstak/jconf.cpp
Graft is forking soon, with updated software released yesterday, to what
will be v8 in Graft (current Graft cryptonight algorithm is graft v7).
This commit updates the `graft` algorithm to recognize the fork and
switch algorithms.
Fork annoucement:
https://www.graft.network/2018/04/12/patch-1-1-1-released-major-network-update-block-65110/
> Update graft algorithm setting for graft fork

- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/amd_gpu/gpu.hpp
- xmrstak/backend/amd/autoAdjust.hpp
- xmrstak/backend/amd/minethd.cpp
- xmrstak/backend/backendConnector.cpp
- xmrstak/cli/cli-miner.cpp
- xmrstak/params.hpp
Allow the usage of non AMD OpenCl devices. This PR should allow the usage of old NVIDIA devices those are not supported by CUDA 7.5+ (e.g. old GTX9XXX).
Some devices like Nvidia Kepler GPUs perform sometimes a little bit better than with CUDA. Very new NVIDIA devices shows a bad performance with OpenCl (compared to CUDA).
- add CLI flag to explicitly use non AMD OpenCL and devices
- adjust OpenCL output (use OpenCL instead of AMD if --openCLVendor is sued)
- optimize NVIDIA OpenCL auto suggestion
> allow non AMD OpenCL driver and devices

- CMakeLists.txt
Use EXECUTABLE_OUTPUT_PATH and LIBRARY_OUTPUT_PATH to control the path to which the executable and libraries are installed.
> Use EXECUTABLE_OUTPUT_PATH and LIBRARY_OUTPUT_PATH

- xmrstak/net/jpsock.cpp
clang warns about the wrong usage:
```
xmrstak/net/jpsock.cpp:232:30: warning: parentheses were disambiguated as redundant parentheses around declaration of variable named 'job_mutex' [-Wvexing-parse]
std::unique_lock<std::mutex>(job_mutex);
^~~~~~~~~~~
xmrstak/net/jpsock.cpp:232:30: note: add a variable name to declare a 'std::unique_lock<std::mutex>' initialized with 'job_mutex'
std::unique_lock<std::mutex>(job_mutex);
```
> fix wrong unique_lock usage

- xmrstak/jconf.cpp
Official Announcement: https://intensecoin.com/2018/04/16/imminent-hard-fork-and-network-attack/
Sorry, I'm dumb as a brick and accidentally closed the other pull request.  Sigh.
Note: Intense Coin already exists in README.md w/link to the main site and already mentioned in xmrstak/pools.tpl.  This simply updates the fork block version to Cryptonight v1 as v4 for Intense Coin.  The pool example is the official pool, which oddly does not have a host pointed to it (hence the bare IP).
> Update ITNS with v4 fork to CN v1

- README.md
- xmrstak/jconf.cpp
- xmrstak/pools.tpl
> Add turtlecoin as a config option

- xmrstak/backend/amd/amd_gpu/gpu.cpp
- fix that to much OpenCL calls whre used if cache is disabled
This fix allow to workaround the broken MAC OSX OpenCl #1438.
> fix that cli option `--noAMDCache`

- xmrstak/backend/globalStates.hpp
- xmrstak/backend/miner_work.hpp
- xmrstak/backend/pool_data.hpp
- initialize miner_work iPoolId in the default constructor with the invalid pool id
- move definition of `pool_data` into an own file (avoid ring includes)
If we lost the connection to the pool or at the start we set the miner_work to a default constructed work element. In this work the stalled flag is enabled and the pool id is set to default. In the previous code the id was default zero `0` which represent the dev pool. If we get the connection to a new pool or the old one after we lost the connection the previous pull in [executor.cpp:380](https://github.com/fireice-uk/xmr-stak/blob/26a5d65f12b2f19a0a3ece39a2bc64718796367b/xmrstak/misc/executor.cpp#L380) is used to store the last nonce. The nonce is wrongly passed to the dev pool.
I do not know if the old behavior is critical but it is …
> set correct `iPoolId` for miner_work

- xmrstak/backend/amd/amd_gpu/gpu.cpp
When trying to use the latest `dev` branch to connect to a sumo server, I am getting:
```
[2018-05-08 12:53:32] : Pool logged in.
[2018-05-08 12:53:32] : Error CL_INVALID_ARG_INDEX when calling clSetKernelArg for kernel 1, arugment 4(input buffer).
[2018-05-08 12:53:32] : Error CL_INVALID_ARG_INDEX when calling clSetKernelArg for kernel 1, arugment 4(input buffer).
[2018-05-08 12:53:32] : Error CL_INVALID_KERNEL_ARGS when calling clEnqueueNDRangeKernel for kernel 2.
[2018-05-08 12:53:32] : Error CL_INVALID_KERNEL_ARGS when calling clEnqueueNDRangeKernel for kernel 2.
...
```
where this last error gets repeated forever.
I bisected the problem to the #1512 merge (adding stellite support), then further tracked it down to the condition for stellite missing an `==` (see the commit).
> Fix condition on stellite check

- xmrstak/net/jpsock.cpp
It could be that the event to update the pool job is faster processed than the current job of the pool is updated.
To avoid this the trigger for the event with a new job update is moved after the current pool job update.
> fix possible race condition in jpsock

- THIRD-PARTY-LICENSES
- xmrstak/backend/amd/minethd.cpp
- xmrstak/backend/amd/minethd.hpp
- xmrstak/backend/backendConnector.cpp
- xmrstak/backend/cpu/minethd.cpp
- xmrstak/backend/cpu/minethd.hpp
- xmrstak/backend/globalStates.cpp
- xmrstak/backend/globalStates.hpp
- xmrstak/backend/nvidia/minethd.cpp
- xmrstak/backend/nvidia/minethd.hpp
- xmrstak/cpputil/LICENSE.txt
- xmrstak/cpputil/read_write_lock.h
~~fix #1505~~
~~fix or reduce #1337 #1222~~
- remove switch_work in all classes `minethd`
- move `consume_work` into `globalStates`
- remove the limit that each worker thread must be consume a job before we can receive a new job. 
- miner should not freeze if one GPU is hanging
In the previous implementation it was possible that a worker thread consumed and already old job if the pool is sending jobs faster than a batch of nonces is calculated. The reson is that the current implementation force that each worker must consume the oldest job in the queue before a new job can be added. On a GPU the time to process a job (a batch of nonces) before checking again if the job has changed much longer than on a CPU. A GPU needs typical ~1 sec+ (slow GPUs sometimes 10sec).
example of the PR behavior …
> fix job consume

- xmrstak/cli/cli-miner.cpp
- xmrstak/params.hpp
Add options `--benchwait` and `--benchwork` to tune the waiting and working of the benchmark
Supplying those without also supplying `--benchmark` is left as an exercise in futility and end-user intelligence test (does nothing)
> Add options to set wait/work time for benchmark

- xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
If CUDA 9.X is used and the miner is compiled for `sm_70` and used with Volta GPUs than the miner
deadlocks if `threads` is not a multiple of `32`.
- use `__activemask()` to get all active lanes
> fix possible deadlock with Volta

- xmrstak/backend/amd/minethd.cpp
- xmrstak/backend/cpu/minethd.cpp
- xmrstak/backend/globalStates.cpp
- xmrstak/backend/nvidia/minethd.cpp
- avoid that a nonce which not fits to the current job is used (check jobId after start nonce is consumed)
- move jobId check into the if condition to get a new bunch of nonces
- CPU: add jobId validation after the start nonce is consumed
This bug was introduced with #1526
> fix duplicated nonce usage

- xmrstak/backend/cpu/crypto/cryptonight_aesni.h
This is a replacement PR for #1585, thank you @jdmedeiros for pointing us to this code snipped and providing a fix for the intel compiler.
The define of `_mm256_set_m128i` is not needed and avoid intel compiler throws a warning about it.
> remove definition of `_mm256_set_m128i`

- doc/compile_Linux.md
- doc/compile_Windows.md
AMD has removed the AMD APP SDK links from the website. The AMD employes in the AMD formum posted links to there Dropbox where the SDK can be downloaded)
> fix broken AMD APP SDK download links

- xmrstak/jconf.cpp
This fixes the rejected shares issue (#1644) when miners set the currency to 'electroneum'. A simple set of the fork version for the currency
> Fixed fork version for currency 'electroneum'

- README.md
- xmrstak/jconf.cpp
- xmrstak/pools.tpl
- add ryo currency
- update documentation
> add ryo currency

- xmrstak/backend/amd/minethd.cpp
- xmrstak/backend/cpu/minethd.cpp
- xmrstak/backend/nvidia/minethd.cpp
- xmrstak/misc/executor.cpp
- xmrstak/net/msgstruct.hpp
fix #1708
The extension of the job result contains the wrong algorithm used to create the nonce.
The fix provide now the correct used algorithm even if the coin is forking to a new algorithm.
- forward the used algorithm from the miner
- extent constructor of `job_result`
- tested different coins with our mock-up pool
> fix wrong miner algorithm in result data

- xmrstak/config.tpl
- xmrstak/jconf.cpp
- xmrstak/misc/console.cpp
- xmrstak/misc/console.hpp
Right now the output is buffered with the libc default policy if `flush_stdout` is set to false. This means that if the output is the terminal (`stdout`) it will be line-buffered (except in Windows, where it's unbuffered), but if it isn't then it will be block-buffered, which becomes too slow to pipe to other program or a file. Note that when `flush_stdout` is set to true, stdout is flushed **twice** on each line.
Since those are all the possible use cases, with this PR the output will be line-buffered and flushed **only once** in all cases and therefore no config entry will be necessary.
Edit: The behaviour of Windows caught me off-guard, so I had to revert the initial modification I made, force full-buffering for everything and do the flush manually. Now it works the same across all OS. …
> Buffer output in each line

- doc/FAQ.md
- doc/compile.md
- scripts/build_xmr-stak_docker/build_xmr-stak_docker.sh
Just a few grammar fixes in the docs.
Also a remark on fixing `mmap alloc failed` on Arch Linux and its derivatives. It should also be relevant for [Fedora](https://ask.fedoraproject.org/en/question/41559/has-etcsysctlconf-been-deprecated-on-fedora-20/) but I'm not its user (and didn't bother checking via VM or docker), needs confirmation from actual ones.
> Grammar fixes; mmap alloc failed error remark for Arch Linux.

- README.md
- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
- xmrstak/backend/amd/amd_gpu/opencl/wolf-aes.cl
- xmrstak/backend/cpu/crypto/cryptonight_aesni.h
- xmrstak/backend/cpu/minethd.cpp
- xmrstak/backend/cryptonight.hpp
- xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
- xmrstak/jconf.cpp
- xmrstak/pools.tpl
solve #1688
- add cryptonight_heavy derivate cryptonight_bittube2
- add coin bittube
- remove coin ipbc because this coin is now called bittube
I keep the algorithm `cryptonight_ipbc` because it is not clear if another coin is using the same algorithm.
Maybe we remove `cryptonight_ipbc` after the next release.
The CPU implementation based on https://github.com/ipbc-dev/bittube-miner.
> cryptonight_bittube2

- xmrstak/backend/amd/amd_gpu/opencl/wolf-aes.cl
OpenCl 1.2.is not allowing the subscript operator on buildin vector types.
fix: use `.sX` to access vector components
> fix broken OpenCL 1.2 support

- README.md
- xmrstak/jconf.cpp
- xmrstak/pools.tpl
Hi @psychocrypt,
This PR is linked to (https://github.com/fireice-uk/xmr-stak/pull/1549)
QRL hashpower is over 5MH/s:
You can check in some of the existing mining pools (just a couple of links as an example):
http://qrl.quantapool.com/
http://qrlmining.info/
https://qrl.herominers.com/
> adding qrl as a config option

- xmrstak/backend/amd/minethd.cpp
- xmrstak/backend/amd/minethd.hpp
- xmrstak/backend/cpu/crypto/cryptonight_aesni.h
- xmrstak/backend/cpu/minethd.cpp
- xmrstak/backend/cpu/minethd.hpp
- xmrstak/backend/nvidia/minethd.cpp
- xmrstak/backend/nvidia/minethd.hpp
xmr-stak has several implementations for multi hash per thread.
The results into 3 intepedent implementations.
Each time the algorithm must be changed the possibility to introduce errors is very large.
- unify the different cryptonight CPU implementations
- simplify the function selection array to find the specilized cryptonight implementation
Note: I tried to implement all as recursive unrolling with templates because I am no fan of macros. The result was a little bit slower code. Therefore I decide to use the ugly macros to implement it.
The new code is on my laptop `Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz /4MiB cache)` for cryptonight_lite with 4 hashes per thread slidly faster than the old implementation.
Never the less I will test a few more CPUs.
The reason why I have not reused …
> unify cpu cryptonight implementations

- xmrstak/backend/amd/amd_gpu/gpu.cpp
During the initialization of the compile parameter for OpenCL it could be that the
fixed size buffer is to small. To avoid this we are now using `std::string`.
There is no problem by using `std::string` because this part of code is not performance critical.
I marked it as bug because I got this error yesterday.
> OpenCL: avoid out of memory access

- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
If the first bit of the nonce is `1` (this is very often if we use a nicehash pool)
than it could be that some OpenCL implementations handle the 64bit representation of the 32bit
nonce on the device side as signed integer.
During a right bitshift we pull wrong ones from the wrong higher part of the 64bit
nonce representation into the 32bit part of the nonce.
The result will be that the computed share is invalid.
- explicit cast the nonce on the device to `uint` to avoid any side effects
> fix nicehash `invalid results`

- doc/compile_Linux.md
dropbox link is broken
Add the fix to the correct branch: original PR was #1824
> AMD APP SDK 3.0 url fix

- xmrstak/backend/amd/amd_gpu/gpu.cpp
Avoid that a OpenCL binary from the cache is used if the driver or xmr-stak version has changed.
> avoid OpenCL binary missmatch

- xmrstak/backend/amd/jconf.cpp
There is a copy past mistake tha tthe type of the variable `memChunk` is not tested.
> fix that type of `memChunk` is not tested

- xmrstak/misc/executor.cpp
Change time point used for socket error in json report. Use correct value from socket error log vector.
Fix for issue https://github.com/fireice-uk/xmr-stak/issues/1084
----------------------------------------
> Correct api.json information

- xmrstak/misc/telemetry.cpp
- xmrstak/misc/telemetry.hpp
Add simple locking to telemetry class, since both push and calc methods modify the data buckets and pointers,  this avoids race conditions and bucket corruption.
Hoping this solves occasional "missing stats" or inaccuracy that could not be tracked down to anything but "thread timing mystery".  It does seem to standardize my hashrates as shown which I take to mean it's more accurate.
Regardless it doesn't seem to hurt.
> telemetry: Add mutex to avoid push during recalc and other races

- CMakeLists.txt
- extent MSVC workaround for CUDA to 10.0
- add compute architecture 75 if CUDA 10.0 is found
> add CUDA 10.0 support

- xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
Read memory in bigger chunks per thread to increase the used memory bandwith.
Use for Kepler and Fermi GPUs the old autosuggestion instead of the new settings for cryptonight_v8.
> CUDA: tine cryptonight_v8

- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
With rocm we fighted very long with invalid shares. This is now solved with rocm 1.9 and
this tiny fix.
It is not fully clear where a memory optimization is kicking in and break the kernel `Groestl` if the variables `M` and `H` are not `volatile`.
The performance ill not change with this fix.
The fix is tested with rocm 1.9 with a VEGA64 and a RX570
> fix invalid shares

- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/cpu/minethd.cpp
Compilers complain about these two spots in new code
The cpu fix was to make sure the new function hits return no matter what happens
The fix in amd code just applies the same as the if statement above the new one, simply missing "insurance" parenthesis
```
[ 46%] Building CXX object CMakeFiles/xmr-stak-backend.dir/xmrstak/backend/cpu/minethd.cpp.o
/usr/src/xmr-stak/xmrstak/backend/cpu/minethd.cpp:473:1: warning: control may reach end of non-void function [-Wreturn-type]
}
^
1 warning generated.
```
```
[ 92%] Building CXX object CMakeFiles/xmrstak_opencl_backend.dir/xmrstak/backend/amd/amd_gpu/gpu.cpp.o
/usr/src/xmr-stak/xmrstak/backend/amd/amd_gpu/gpu.cpp:380:9: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
if(ret = …
```
> Fix two new warnings within new code

- xmrstak/backend/cpu/minethd.cpp
Fix wrong warning about unknown ASM type
> CPU: fix logical error

- xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
- Use volatile pointer to be sure that the compiler is not caching the values.
- change most places with type `u64` to `uint64_t`
> CUDA: use volatile pointer

- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
In the current implementation the bit align is using signed integer which results in pulling in
ones in the case the sign bit is set.
- cast to unsigned integer before using bitshift
> fix right bitshift in `amd_bitalign`

- xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
- xmrstak/backend/nvidia/nvcc_code/cuda_fast_int_math_v2.hpp
- remove helper array to perform division
- tweak `get_reciprocal`
thx @SChernykh for this nice tweak
> NVIDIA: tweak `get_reciprocal`

- xmrstak/backend/backendConnector.cpp
- xmrstak/backend/nvidia/minethd.cpp
- xmrstak/backend/plugin.hpp
Allow to ship the miner with multiple cuda backends those depends on different driver versions.
This will allow to support Turing/Volta and old Fermi GPU within one release.
- add support to search for the first working CUDA backend
- add some more messages to support better debugging (if a user has some issues)
If you have any issues please report which binary you used. Both binaries should be able to run with cuda8+.  It would be nice if someone can test both binaries on a system with CUDA10 and with CUDA8/9.X.
If something is not working please provide all output from the terminal.
- xmr-stak_cuda8: https://mega.nz/#!8WZGzIoI!eaweNxWegtFOFX4x6Ci4BT1UJaiSeJJJPPNQJduyZ9Q
- xmr-stak_cuda10: https://mega.nz/#!lOYSXIoI!EebK8gku_kgzZrwIcSdd02tFWFHt6GAguoiaYuCUj90
```
Checksums sha256: …
```
> NVIDIA: support for multiple CUDA libs

- xmrstak/misc/telemetry.cpp
- xmrstak/misc/telemetry.hpp
With #1845 a race condition during the telemetry update is solved.
The problem is that the used mutex is blocking all threads from updating the metrics during
the statistics are calculated.
- introduce a mutex per miner thread
> reduce blocking during metric update

- xmrstak/backend/amd/amd_gpu/opencl/fast_int_math_v2.cl
Fix the fix from #1945. The initial fix produces invalid results.
> fix AMD driver 14

- xmrstak/jconf.cpp
Graft is forking to CNv2 (or "v8") in [just over a week](https://www.graft.network/2018/10/23/graft-anti-asic-major-network-update-1-5-on-october-31-2018/) with major version 11.  This PR updates the `graft` coin setting to recognize it.
> Update for upcoming Graft CNv2 fork

- xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
In the cuda backend for monero we start always twice as much threads as needed.
Those threads are than removed after the AES matrix is copied to the shared memory.
Never the less it is the result of an copy past bug.
- start correct number of threads for `monero`
> NVIDIA: fix wrong number of threads

- doc/compile.md
Place detailed CUDA information in compile docs, to avoid repeating it 9729364 times manually in Issues
> (doc/compile) Add better CUDA SDK vs Driver information

- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
- xmrstak/backend/amd/amd_gpu/opencl/fast_div_heavy.cl
optimize the devision in cryptonight_heavy and cryptonight_haven
import of https://github.com/xmrig/xmrig-amd/pull/185/commits/5d9b9334654df25cea7707f667990fd1577ed290
> AMD: speedup cryptonight_heavy division

- xmrstak/backend/backendConnector.cpp
If CUDA is loaded before AMD but no CUDA is available it can be happen that the embadded OpenCL code is empty.
This is only an issue if the binary is builded static on a different system.
To be sure that this behavior is not a result of an invalid memory access I checked the "broken" binary with valgrind. Valgrind shows no issues.
> change load order for backends

- xmrstak/backend/nvidia/nvcc_code/cuda_aes.hpp
- xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
Use only the half AES matrix and compute the other half in place.
This PR increases the possible occupancy.
> CUDA: reduce cn-v8 shared mem footprint

- xmrstak/backend/amd/amd_gpu/opencl/fast_div_heavy.cl
optimize cryptonight_heavy diff
> OpenCL: optimize cn-heavy div

- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
- remove useless `clFinish`
- avoid download num threads for skein&co and start always as much threads as in all other kernel (terminate useless threads)
> OpenCL reduce API overhead

- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
- change a few 64bit variables into 32bit.
- provide defines type qualified
> AMD: use more 32bit operations

- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
- xmrstak/backend/amd/amd_gpu/opencl/fast_int_math_v2.cl
- remove lookup table for reciprocal calculation
- optimize division
> OpenCl: optimize cn-v8 div

- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
small optimization for non cryptonight_v8 algorithms
- remove tmp variable (looks like it is not possible for the compiler to remove it for non cn-v8 algos)
- join precompiler regions for cn-v8
@fireice-uk : please ignore the white space changes. I will remove all spaces with tabs before the next release.
> OpenCL: cnv8 optimization

- xmrstak/backend/amd/amd_gpu/gpu.cpp
Disable compatibility mode if intensity is a multiple of worksize. In that case enabled compaibility mode will only slow down the miner.
> OpenCL: comp mode optimization

- xmrstak/backend/amd/amd_gpu/gpu.cpp
Due to a wrong implementation clamp was not working.
> fix clamp implementation

- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
- xmrstak/backend/amd/amd_gpu/opencl/fast_int_math_v2.cl
- fix broken compile: change used `ULL` to `UL` because `UL` is defined as 64bit
- fix memory copy to shared memory via vload8 (alignment issue of the shared memory)
> OpenCl: fix NVIDIA

- doc/tuning.md
- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/amd_gpu/gpu.hpp
- xmrstak/backend/amd/config.tpl
- xmrstak/backend/amd/jconf.cpp
- xmrstak/backend/amd/jconf.hpp
- xmrstak/backend/amd/minethd.cpp
- xmrstak/backend/amd/minethd.hpp
Add an option to brute force intensity settings and lock in at the intensity with the highest hashrate.
- update documentation of the `interleave` option to mention the side effect with `auto-tune`
- disable `interleave` auto adjustment if `auto-tune` is enabled
- jconf: add `auto-tune` as optional option
> OpenCL: auto tuning option

- xmrstak/backend/amd/jconf.cpp
The default value for interleave was wrongly set to 50.
Remove the value and take the default from the default constructor instead of side channeling it from the json parser.
> fix default interleave value

- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/amd_gpu/gpu.hpp
- xmrstak/backend/amd/autoAdjust.hpp
- xmrstak/backend/cpu/autoAdjust.hpp
- xmrstak/backend/cpu/autoAdjustHwloc.hpp
- xmrstak/backend/cpu/crypto/cryptonight_common.cpp
- xmrstak/backend/cpu/minethd.cpp
- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
- xmrstak/misc/coinDescription.hpp
In the current implementation the POW algorithm in dev pool section of a
currency will not be taken into account during the binary creation.
This PR changes the behavior and allow to create binaries for more than two POW algorithms.
- add helper method `GetAllAlgorithms()` to get all active POW
algorithms
- select max scratchpad memory size based on the dev pool and user
algorithms
> refactor POW selection algorithm

- README.md
- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
- xmrstak/backend/amd/amd_gpu/opencl/fast_int_math_v2.cl
- xmrstak/backend/amd/autoAdjust.hpp
- xmrstak/backend/cpu/crypto/cryptonight_aesni.h
- xmrstak/backend/cpu/minethd.cpp
- xmrstak/backend/cryptonight.hpp
- xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
- xmrstak/jconf.cpp
- xmrstak/misc/executor.cpp
- xmrstak/net/jpsock.cpp
- xmrstak/pools.tpl
TurtleCoin Release Notes: https://github.com/turtlecoin/turtlecoin/releases/latest
Added as algorithm: `cryptonight_turtle`
Note: Auto-switching is not possible with this PR as TurtleCoin uses a parent/root block header that results in the pools (and thus the miners) always seeing the block MajorVersion as 1 (unless it's updated as part of a fork). We don't currently do this and have no immediate plans to do so; however, please see PR #2177 which adds support for using a MajorBlock version supplied by a pool with support to do so.
Addresses #2159 & #2174 
Dero Gold is already using the algorithm, you can test the build against one of their pools
```javascript
"pool_list": [
{
"pool_address": "dego.cnpool.cc:32550",
"wallet_address": …
```
> Add Support for TurtleCoin Upcoming Fork

- xmrstak/backend/amd/amd_gpu/gpu.cpp
Fix message with the maximal allowed work size if cryptonight_gpu is used.
> OpenCL: fix work size message

- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
Windows driver creates wrong code if unroll is used.
> OpenCL: fix Blake hashing

- README.md
- xmrstak/jconf.cpp
- rename `Intense` to `Lethean`
- remove `masari` and `stellite`, both hase forked to a currently
unsupported algorithm
> coin cleanup

- xmrstak/backend/nvidia/nvcc_code/cuda_cryptonight_gpu.hpp
Remove `static constexpr` within the global kernel. This is not
supported by all CUDA versions.
> CUDA. fix static in global kernel

- xmrstak/backend/cryptonight.hpp
- xmrstak/net/jpsock.cpp
During the implementation of `cryptonight_gpu` we missed to add the name
of the algorithm to jpsock. 
This fix solves a incompatibility with xmrig-proxy.
- add function to translate an algorithm into a name.
reported by @xmrig
> fix missing algorithm name

- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
@xmrig provided the information that the driver 19.2.1 for vega also
create invalid results if pragma unroll is used for the groestl algo.
> OpenCL: fix groestl

- xmrstak/backend/cpu/autoAdjust.hpp
- xmrstak/backend/cpu/autoAdjustHwloc.hpp
To avoid that a miner is waisting power with there CPU to mine cn_gpu the
auto suggestion will comment out the config.
> cn_gpu: disable auto suggestion for CPU

- xmrstak/backend/amd/amd_gpu/opencl/cryptonight_gpu.cl
- xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
- xmrstak/backend/nvidia/nvcc_code/cuda_cryptonight_gpu.hpp
This PR includes #2222
Combine the shared memory for a hash within one struct.
Reduce the shared memory footprint per hash by 64 byte.
> CUDA/OpenCL: use shared mem object

- xmrstak/backend/amd/amd_gpu/opencl/cryptonight_gpu.cl
The OpenCl version of the blockchain driver is not understanding if
apointer to a pointer points into shared memory and throw an error
during the compilation.
- revert the usage of the struct to group all shared memory arrays
> OpenCl: fix blockchain driver support

- xmrstak/backend/cryptonight.hpp
The iterations of the Zelerius algorithm in the next hard fork will be 0x60000 it seems by mistake 0x6000 was set. Thanks!
> Please fix Zelerius iterations

- CMakeLists.txt
Add `OCL_ROOT` envvar support for Windows OCL SDK Light autodetection and prefer it over AMD APP SDK if both are installed.  Tested on Win7 with both SDKs installed (and all CUDAs and Intel OpenCL SDK also... haha) it still selected properly.
`OCL_ROOT` envvar can be preloaded with alternate OpenCL and I have also tested using it to point to nVidia OpenCL and etc, CMake finds all and result builds fine.  Older versions you would have used `AMDAPPSDKROOT` envvar to do the same thing, but when `OCL_ROOT` exists it will take precedence over all.
Moved `CMAKE_PREFIX_PATH` handling all to the top, previously the `$ENV{CMAKE_PREFIX_PATH}` would be added to the list twice (once at top and once after AMD path).
Fixes #2235 proper user expectation that it should detect automatically and build …
> CMakeLists.txt: Adjust OpenCL probing to find OCL SDK Light

- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
Vega GPUs create still invalid shares on windows 19.X and 18.7+ driver for cn_v8 and cn_heavy.
> OpenCL: fix Vega invalid shares (windows)

- xmrstak/backend/amd/amd_gpu/gpu.cpp
Since #2268 the multi gpu support is broken. It is not possible to have more than one opencl context in a process.
Use one OpenCl context for the process instead per GPU.
> OpenCl: fix multi gpu support

- CMakeLists.txt
- xmrstak/backend/amd/OclCryptonightR_gen.cpp
- xmrstak/backend/amd/minethd.cpp
- xmrstak/backend/cpu/crypto/CryptonightR_gen.cpp
- xmrstak/backend/cpu/crypto/asm/cnR/CryptonightR_template.S
- xmrstak/backend/cpu/crypto/asm/cnR/CryptonightR_template.asm
- xmrstak/backend/cpu/crypto/asm/cnR/CryptonightR_template.h
- xmrstak/backend/cpu/crypto/asm/cnR/CryptonightR_template.inc
- xmrstak/backend/cpu/crypto/asm/cnR/CryptonightR_template_win.inc
- xmrstak/backend/cpu/crypto/asm/cnR/CryptonightWOW_template.inc
- xmrstak/backend/cpu/crypto/asm/cnR/CryptonightWOW_template_win.inc
- xmrstak/backend/cpu/crypto/asm/cryptonight_v8_double_main_loop_sandybridge_linux.inc
- xmrstak/backend/cpu/crypto/asm/cryptonight_v8_double_main_loop_sandybridge_win64.inc
- xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop.S
- xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop.asm
- xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop_ivybridge_linux.inc
- xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop_ivybridge_win64.inc
- xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop_ryzen_linux.inc
- xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop_ryzen_win64.inc
- xmrstak/backend/cpu/crypto/cryptonight.h
- xmrstak/backend/cpu/crypto/cryptonight_aesni.h
- xmrstak/backend/cpu/crypto/variant4_random_math.h
- xmrstak/backend/cpu/minethd.cpp
- xmrstak/backend/cpu/minethd.hpp
- xmrstak/backend/cryptonight.hpp
- xmrstak/backend/nvidia/minethd.cpp
- xmrstak/backend/nvidia/nvcc_code/cryptonight.hpp
- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
- add cryptonight_r assembly
- fix cryptobight_v8 assembly
> assembly patching

- xmrstak/backend/cpu/crypto/cn_gpu_avx.cpp
- xmrstak/backend/cpu/crypto/cryptonight_common.cpp
This makes CN_GPU compile on Clang 3.5, and then furthermore allow allocations without HUGETLB (with warning) since it is faster than always-slow mode even though not ideal.
> CN_GPU: Fix old compilers and old kernels (Clang 3.5 tested, without CONFIG_HUGETLBFS)

- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
- xmrstak/backend/amd/autoAdjust.hpp
- xmrstak/backend/amd/minethd.cpp
- xmrstak/backend/miner_work.hpp
- xmrstak/backend/nvidia/minethd.cpp
- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
- xmrstak/backend/nvidia/nvcc_code/cuda_keccak.hpp
- xmrstak/cli/cli-miner.cpp
- xmrstak/net/msgstruct.hpp
fix  #2278 #2233 
Since masari increased the block size the miner crashed each time it
gets connected with a masari pool.
This PR extent the possible size of a block to 128 byte and updated the
kernel.
> fix masari

- xmrstak/backend/cpu/crypto/cryptonight_aesni.h
fix #2307
If the miner changed the pool (user pool or dev pool) and the network
block of monero has not changed the miner switch to the non asm version.
Add check if the hash function has changed. If the hash function not
point to the asm version the ASM function is recreated.
> CPU: fix cryptonight_r slowdown

- xmrstak/backend/cpu/crypto/cryptonight_aesni.h
If cryptonight_gpu is used in the dev pool and a cryptonight_v8 derived
algorithm than cryptonight_gpu will create wrong results if v8 was
running as non ASM version.
I added the rounding mode for cn_gpu by accident in an older PR to the wrong place within the code.
> fix cn_gpu rounding mode selection

- xmrstak/backend/cpu/cpuType.cpp
The OS is able to disable avx. In that case our avx detection is wrong.
See xmrig issue: https://github.com/xmrig/xmrig/issues/951
Import fix: https://github.com/xmrig/xmrig/commit/6052da3c4399514c95245b2d342f04baa20958db#diff-92fa29935c136762d35981769ac79f52
thx @xmrig for the notification.
> fix avx detection

- CMakeLists.txt
Missing the proper subdir for OSX NVRTC hunting (just `lib` they don't use lib64, x64, etc)
and some tabs where four spaces (or nothing) belonged
> Repair OSX CUDA searched-path for NVRTC

- xmrstak/backend/amd/OclCryptonightR_gen.cpp
- xmrstak/backend/amd/OclCryptonightR_gen.hpp
- xmrstak/backend/amd/amd_gpu/gpu.cpp
Fix a memory leak that the OpenCL programs was not freed correctly.
First solved by @xmrig
This bug effects only cryptonight_r.
> OpenCL: fix memory leak

- xmrstak/cli/cli-miner.cpp
Add the possibility to run a simplified miner configuration.
IN the case the user like to use this mode the number of question to
setup the miner will be reduced to a minimum.
Additional changes:
- add default values for `yes/no` questions
If the simple mode is use the questions are:
- Please enter the currency that you want to mine:
- Pool address: 
- Username (wallet address or pool login):
- Password (mostly empty or x):
- Does this pool port support TLS/SSL? Use no if unknown. (y/N)
The last two can be answered by pressing ENTER without typing.
> simple miner startup

- xmrstak/backend/amd/OclCryptonightR_gen.cpp
- xmrstak/backend/amd/OclCryptonightR_gen.hpp
- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/amd_gpu/gpu.hpp
- xmrstak/backend/amd/amd_gpu/opencl/cryptonight_r.rtcl
- xmrstak/backend/amd/amd_gpu/opencl/cryptonight_r_def.rtcl
Instead of creating a new kernel for each block we pre-build 25 kernel within a chunk.
This reduces the calls to `clCreateProgramWithSource` which creates the leaks and will crash the miner after a few hours.
Workaround was first introduced by @SChernykh in xmrig-amd
- add helper: `search_program()`
- split OpenCL runtime code into definition and body for `cryptonight_r`
> AMD: workaround driver memory leaks

- xmrstak/cli/cli-miner.cpp
Simple starts requires always user interactions if config.txt and
pools.txt is not available.
This PR asked the user only on the first advanced option if he/she
preferse the simple start or an advanced mode.
If all parameter are already defined via command line options than the
question will never be shown.
> fix simple start

- xmrstak/backend/amd/minethd.cpp
- xmrstak/backend/cpu/minethd.cpp
- xmrstak/backend/iBackend.hpp
- xmrstak/backend/nvidia/minethd.cpp
Since the dev pool is sometimes using another POW than the user pool the
hash date can strongly increase or decrease.
In a case of a hash rate drop a monitoring software could trigger a
wrong miner restart.
- use the hash rate calculated during the user pool mining to
interpulate the number of hashes during the dev pool mining so that the
statistics stay constant.
> avoid hash rate drop during dev pool mining

- xmrstak/misc/telemetry.cpp
- xmrstak/misc/telemetry.hpp
Allow that the web interface/json api and the command line view can
create the hash rate statistics concurrent.
> concurrent hash rate calculation

- xmrstak/cli/cli-miner.cpp
> fix benchmark mode

- README.md
- xmrstak/jconf.cpp
- xmrstak/pools.tpl
The name of the coin has changed https://medium.com/torque/rebranding-stellite-xtl-to-torque-xtc-14ae0638ef35
> change stellite to torque

- xmrstak/backend/cpu/autoAdjustHwloc.hpp
- xmrstak/backend/cpu/minethd.cpp
If hwloc autoconf does not work, fall back to the basic autoconf.
This provides a better guess for some CPUs for which hwloc autoconf fails. This was marked as "TODO" in the code.
> Fallback from hwloc autoconf to basic autoconf

- xmrstak/backend/amd/minethd.cpp
- xmrstak/backend/iBackend.hpp
- xmrstak/backend/nvidia/minethd.cpp
- xmrstak/misc/executor.cpp
For each accepted/rejeced share, print responsible GPU and pool.
@psychocrypt Moved this feature into a separate pull request
> Print responsible GPU and pool for accepted/rejected shares

- xmrstak/misc/uac.cpp
These conditions combined make the miner terminate:
- `"use_slow_memory"` == `"warn"`
- `--noUAC`
- Windows 7 or 8
[The code](https://github.com/fireice-uk/xmr-stak/blob/a5b8fb741b17307871681ef0eab6fd4cf224b6df/xmrstak/cli/cli-miner.cpp#L769) where the termination happens. This breaks the expected behavior of the `warn` option on Win 7 and 8,
> Don't fail with "use_slow_memory" == "warn" and --noUAC on Windows 7, 8

- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
- use native rocm shuffle function
- change local memory access pattern
> OpenCL: rocm shuffle

- xmrstak/backend/amd/autoAdjust.hpp
- xmrstak/backend/nvidia/autoAdjust.hpp
- xmrstak/cli/cli-miner.cpp
- xmrstak/params.hpp
New CLI arguments for enabling/disabling specific GPUs:
```
--amdGpus GPUS             indices of AMD GPUs to use. Example: 0,2,3
--nvidiaGpus GPUS          indices of NVIDIAGPUs to use.
```
Disabled GPUs are commented out in nvidia.txt or amd.txt.
This is useful for automated starts on specific GPUs without config editing.
> Enabling/disabling GPUs from CLI

- xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
- #2443 broke cryptonight_v8 and dereived POW e.g. masari,
rcyptonight_v8_half
- fix also `cryptonight_turtle`
fix #2464
> NVIDIA: fix cryptonight_v8 and derived pows

- xmrstak/backend/nvidia/nvcc_code/cryptonight.hpp
- xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
- with #2443 the possible maximum number of threads per block was
reduced because phase3 used 16 threads per share (is automatically
avoided if thread limit is exeeded)
- warn user if `threads` is to large and adjust to a valid value
should solve: https://github.com/fireice-uk/xmr-stak/issues/2455
> NVIDIA: releax 'threads' config

- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
- xmrstak/backend/amd/amd_gpu/opencl/wolf-skein.cl
fix #2473 
Since AMD driver 19.7.X the miner crashes without any error message.
The driver bug shows up in windows and linux.
The reason for the crash are two for loop.
The workaround is to partly unroll the loops by hand.
> fix AMD driver 19.7.X bug

- xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
- with #2468 I fully break the miner: producing invalid results and not scan all shares
The release 2.10.6 is fully broken for NVIDIA and should not be used.
> NVIDIA: fix broken phase 3

- xmrstak/backend/amd/autoAdjust.hpp
- increase the work size to 16 for cryptonight_gpu for vega GPUs
> AMD: optimize VEGA auto suggestion

- README.md
- xmrstak/jconf.cpp
- remove `turtlecoin`, `xcash` and `loki`
All of this currencies forked to an unsupported POW algorithm.
> remove unsupported currencies

- xmrstak/misc/telemetry.cpp
- xmrstak/misc/telemetry.hpp
solve partly #2514
Remove a mutex which is not needed at all because all data are accessed
from one thread only.
> fix useless mutex

- xmrstak/backend/amd/autoAdjust.hpp
solve #2510
set worksize to 16 instead of 8
> AMD: optimize fiji auto config cn-gpu

- xmrstak/backend/cpu/crypto/cryptonight.h
- xmrstak/backend/globalStates.hpp
- xmrstak/jconf.hpp
- xmrstak/misc/console.hpp
- xmrstak/misc/environment.cpp
- xmrstak/misc/environment.hpp
- xmrstak/misc/executor.hpp
- xmrstak/params.hpp
Since we can not implement clean image book singletons (windows
issues with shared libraries) we used a hierarchical to "emulate"
singletons. During the creation race conditions are possible.
This PR will handle the race-conditions with a mutex, since we pass the
creation of a singleton creation only ones we have no performance issue.
> fix singletons

- xmrstak/backend/amd/autoAdjust.hpp
solve #2509
for RX5700
- use unroll 8 
- use two threads for cryptonight_gpu
> AMD: optimize unroll for rx5700

- xmrstak/backend/amd/minethd.cpp
- xmrstak/backend/cpu/minethd.cpp
- xmrstak/backend/nvidia/minethd.cpp
- xmrstak/backend/nvidia/minethd.hpp
fix #2514
- use `unlock()` instead of `release()`
- fix NVIDIA affinity setting
> fix locking to secure affinity update

- xmrstak/cli/cli-miner.cpp
Since this branch offers only RandomX algorithm, I put correct author names for CPU/GPU mining code.
> Correct authors of RandomX mining code

- xmrstak/backend/cpu/minethd.cpp
- advertise for the cli option `--noTest`
> [RX] advertise for disabling self test

- xmrstak/backend/cpu/hwlocMemory.cpp
- fix warning depricated `hwloc_set_membind_nodeset` (since hwloc 2.0)
> [RX] fix hwloc warning

- xmrstak/cli/cli-miner.cpp
- xmrstak/misc/executor.cpp
- during the start of the miner and the guided setup the tls settings
was ignored.
- fix that parameters from the guided start is passed to the parameter singleton
> [RX] fix irgnored tls on first start

- xmrstak/backend/cpu/crypto/cryptonight_aesni.h
- xmrstak/backend/cpu/minethd.cpp
- xmrstak/backend/cpu/minethd.hpp
- xmrstak/cli/cli-miner.cpp
- xmrstak/net/socket.cpp
fix #2552
The block version must be greater than 0.
This PR also remove some not used functions.
> [RX] fix miner benchmark mode

- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
fix #2564
- add the dataset size to the maximum allowed memory usage
> [RX] NVIDIA: fix auto adjustment

- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
fix #2531
Set number of threads for `cryptonight_gpu `always to `8` and adjust the
number of blocks depending of the free memory.`
> [NVIDIA] fix possible out of memory with auto cfg

- xmrstak/backend/cpu/hwlocMemory.cpp
- fix warning depricated `hwloc_set_membind_nodeset` (since hwloc 2.0)
> fix hwloc warning

- xmrstak/cli/cli-miner.cpp
- xmrstak/misc/executor.cpp
- during the start of the miner and the guided setup the tls settings
was ignored.
- fix that parameters from the guided start is passed to the parameter singleton
> fix tsl not used on first start

- CMakeLists.txt
- xmrstak/backend/backendConnector.cpp
Rename xmr-stak-rx backend libraries to avoid conflicts with xmr-stak
libraries.
fix #2571
> [RX] rename shared libraries

- xmrstak/backend/cpu/minethd.cpp
Fix that memory is not pinned correct because an invalid value for the
affinity was used.
fix# #2587
> [RX] fix memory pinning

- xmrstak/cli/cli-miner.cpp
- xmrstak/misc/executor.cpp
- xmrstak/params.hpp
The miner is collecting system information to improve our support.
Allow the user to disable the transfer of any information to us.
> [RX] disable dev support cli option
