fireice-uk/xmr-stak

- xmrstak/backend/miner_work.hpp
- xmrstak/cli/cli-miner.cpp
- xmrstak/misc/executor.cpp
- add nicehash flag back to `miner_work`
This bug was detected in #2
> fix broken nicehash support

- xmrstak/misc/executor.cpp
Minor change, will merge as son as CI passes.
> Increase the scratchpad size to make sure we don't malform JSON

- CMakeLists.txt
- xmrstak/backend/backendConnector.cpp
- xmrstak/backend/cpu/crypto/cryptonight_common.cpp
- xmrstak/cli/cli-miner.cpp
- xmrstak/misc/uac.hpp
- Add large page initialisation on Windows
- Add a proper UAC manifest requesting elevation when we start
- Fix #4 self_test() - this is integral part of initialisation
> Fix large pages on Windows and make them more user-friendly

- xmrstak/backend/cpu/minethd.cpp
- xmrstak/backend/cpu/minethd.hpp
> Port the crash fix from xmr-stak-cpu

- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
Early returns within a kernel can have unexpected behavior, this strongly depends on the opencl
runtime compiler. To avoid errors all early returns are removed.
There is no negative effect(e.g.performance) if the threads stay alive up to the end of the kernel.
One source for the early return is: http://al-key-opencl.blogspot.de/2014/09/be-careful-not-to-mix-early-return-and.html
This pull request also fix a race condition where all fill the shared memory.
Also a bug introduced with #16 is fixed, because of the early return not was possible that
the last block works with an wrong initilized shared memory (result should be a wrong hash if the result target size is valid).
To review this PR please use the [diff without withe space changes](https://github.com/fireice-uk/xmr-stak/pull/24/files? …
> remove early returns

- xmrstak/backend/amd/autoAdjust.hpp
- xmrstak/backend/amd/config.tpl
Simple removal, doesn't do anything as you already removed the gpu_thread_num == array_size check
> remove the gpu_thread_num safety

- xmrstak/backend/cpu/minethd.cpp
- xmrstak/backend/cpu/minethd.hpp
Order of calls in this PR
1. thd_setaffinity, not in this thread
2. bindMemoryToNUMANode
> Affinity fix version B

- xmrstak/backend/cpu/minethd.cpp
- xmrstak/backend/cpu/minethd.hpp
Order of calls in this PR:
1. bindMemoryToNUMANode
2. thd_setaffinity, not in this thread
> Affinity fix version C

- CMakeLists.txt
add `sm_70` if CUDA 9+ is available
> add NVIDIA Volta support

- doc/tuning.md
- xmrstak/backend/amd/jconf.cpp
Turns out I lied when I said that you removed the check =).
> Proper removal of gpu_thread_num

- xmrstak/backend/plugin.hpp
- xmrstak/cli/cli-miner.cpp
- xmrstak/params.hpp
- search for plugin in
- working directory
- binary directory
- let linux search the plugins (libraries)
This PR is needed to allow `appImage` creation.
> search for linux backend plugins

- doc/compile_Linux.md
- doc/compile_Windows.md
- add CUDA and AMD APP SDK dependency to linux compile guide
- add AMD APP SDK dependency to windows compile guide
> update compile documentation

- .gitignore
- xmrstak/backend/cpu/jconf.hpp
- xmrstak/backend/globalStates.hpp
- xmrstak/cli/cli-miner.cpp
- xmrstak/config.tpl
- xmrstak/donate-level.hpp
- xmrstak/jconf.cpp
- xmrstak/jconf.hpp
- xmrstak/misc/executor.cpp
- xmrstak/misc/executor.hpp
- xmrstak/net/jpsock.cpp
- xmrstak/net/jpsock.hpp
- xmrstak/net/msgstruct.hpp
- xmrstak/net/socket.cpp
This is a very first draft. Lots of deep-running logic changes, so bugs are inevitable.
Uploading this one early so it can be tested. Dev donate is 50% / 4min in this branch to facilitate testing.
Only pool failover is supported. We can leave round-robin until after the release as this is likely to be even more complex.
Config side is not implemented at all yet, you can add pools directly in executor main.
I implemented a mock pool to facilitate testing, see http://github.com/fireice-uk/xmr-pool-mock
**Final tasks before merging**
> Multi-pool final version

- xmrstak/config.tpl
- xmrstak/http/httpd.cpp
- xmrstak/http/webdesign.cpp
- xmrstak/http/webdesign.hpp
- xmrstak/jconf.cpp
- xmrstak/jconf.hpp
HTTP Digest authentication support. Must not be merged before #90 as it is based on top of it.
> HTTP Digest Authentication

- THIRD-PARTY-LICENSES
> Add third-party cc info

- doc/usage.md
> fix wrong box ending

- doc/tuning.md
Documentation: Add environment variables to increase OpenCL memory pool
> AMD: increase memory pool

- CMakeLists.txt
- xmrstak/backend/nvidia/autoAdjust.hpp
- xmrstak/backend/nvidia/minethd.cpp
- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
- check if the gpu architecture is supported by the compiled miner binary
- remove not supported gpus from the auto suggestion
- disallow the selection of a not supported gpu by hand tuning the config
Please review only the second commit.
> check gpu architecture 

- .travis.yml
- CI/checkPRBranch
- forbid PR to master if not from our reposetory and named `dev` or `release-*`
- do not check forks
> forbid PR to master branch

- xmrstak/backend/amd/minethd.cpp
- xmrstak/backend/cpu/minethd.cpp
- xmrstak/backend/iBackend.hpp
- xmrstak/backend/nvidia/minethd.cpp
- xmrstak/config.tpl
- xmrstak/http/webdesign.cpp
- xmrstak/http/webdesign.hpp
- xmrstak/jconf.cpp
- xmrstak/jconf.hpp
- xmrstak/misc/executor.cpp
- xmrstak/misc/executor.hpp
- xmrstak/net/jpsock.cpp
- xmrstak/net/jpsock.hpp
- xmrstak/net/msgstruct.hpp
This is my final feature PR before the release. It implements algo, hashcount, backend and motd extensions.
With regards to motd extension:
- Only English characters supported for now (Unicode needs more thought from the security angle)
- Javascript injection is considered and prevented
- Terminal characters and other rubbish is filtered.
Needs testing, but should be ok. I will update the mock pool to include extensions.
> Network extensions

- xmrstak/misc/executor.cpp
- xmrstak/net/jpsock.cpp
> Fix cases where positive feedback was still occurring.

- xmrstak/misc/executor.cpp
> fix aeon dev pool

- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
fix #130
fix wrong arch comparison
> fix wrong cuda binary arch detection

- .appveyor.yml
- doc/compile_Linux.md
- add copy of openssl libs to appvoyer CI tests
- update windows compile documentation
> fix windows compile documentation

- xmrstak/cli/cli-miner.cpp
- xmrstak/misc/console.cpp
- xmrstak/misc/console.hpp
This should fix the version issue.
> Add windows exit

- xmrstak/jconf.cpp
This change fix #177 and compiler warning too.
> Fix crash on FreeBSD (#177)

- doc/usage.md
add NVIDIA cli options to the help message
fix #161 thx @CircusDad for spotting
> add missing nvidia help to usage.md

- Dockerfile
- doc/usage.md
- scripts/build_xmr-stak_docker/build_xmr-stak_docker.sh
Adding Dockerfile and fixing build_xmr-stak_docker script.
> Adding Dockerfile and fixing build_xmr-stak_docker script

- xmrstak/misc/executor.cpp
This makes the switch message clearer as per #245
> Add custom message for dev -> user pool switch

- README.md
> Really fixing incorrect Releases URL in README.md#Download

- doc/Linux_deployment.md
add warning that portable binaries are experimental
> experimental warning: portable binaries

- README.md
open #311 against the dev branch
> fix Releases link

- doc/FAQ.md
I expect that link is something that would be easily lost if another item is added.
> [docs] Explicitly linked to an implied location

- xmrstak/backend/amd/amd_gpu/gpu.cpp
Cleanup of the x-mas tree code. @psychocrypt 
I think I fixed  a bug here
```
clError = clGetDeviceInfo(....);		
if(clStatus == CL_SUCCESS)
```
As well as doing general clean up - can you see if the code is ok?
> Clean up the x-mas tree

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
add templates with importend information to optimize the support
more information: https://github.com/blog/2111-issue-and-pull-request-templates
> add issue and pull request templates

- doc/tuning.md
- xmrstak/backend/cpu/config.tpl
- xmrstak/backend/cpu/crypto/cryptonight_aesni.h
- xmrstak/backend/cpu/jconf.cpp
- xmrstak/backend/cpu/jconf.hpp
- xmrstak/backend/cpu/minethd.cpp
- xmrstak/backend/cpu/minethd.hpp
The "low_power_mode" option in config.txt can be set to numeral values
between 1 and 5. A value of 5 seems optimal on certain processors
with large L4 cache.
> Extend low_power_mode to do up to 5 cn hashes at a time.

- doc/compile_Windows.md
That's what it's called now: https://i.imgur.com/juZhtyz.png
> Correct name of optional feature

- doc/FAQ.md
I chuckled reading that my virus protection software might flag the miner binary as “male ware,” and rewrote that section of the documentation.
> Grammar and wording regarding virus protection software

- xmrstak/cli/cli-miner.cpp
- xmrstak/jconf.cpp
- xmrstak/misc/executor.cpp
- xmrstak/net/jpsock.hpp
- xmrstak/params.hpp
- Fix CLI startup so that it is possible to supply all arguments for instant launch from the command line
- Make the CLI pool a top priority instead of overwriting other pools
- If the CLI pool is missing login / password, but is in the config, they will be supplied from the config
PR has been tested using our mock pool
> Fix cli questions

- xmrstak/version.cpp
> increase version to 2.1.0

- README.md
please merge after the binaries are tested on a AMD windows system
> add binary checksums for version 2.1.0

- xmrstak/cli/cli-miner.cpp
solve #440 thanks @true-datura for spotting and fixing.
> fix windows compile

- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
handle all error codes from the cuda API calls.
> handle cuda error codes

- .appveyor.yml
> readd appveyor xmr-stak runtime test

- xmrstak/net/socket.cpp
Fix typo in TLS support message
> Fix typo in socket.cpp

- README.md
> Add altcoin list

- xmrstak/cli/cli-miner.cpp
- xmrstak/misc/uac.hpp
Very quick fix - haven't even built it yet.
> Stop UAC popup for elevated ctx

- xmrstak/backend/amd/minethd.cpp
- xmrstak/backend/cpu/minethd.cpp
- xmrstak/backend/nvidia/minethd.cpp
- xmrstak/cli/cli-miner.cpp
- xmrstak/misc/executor.cpp
- xmrstak/misc/telemetry.cpp
- xmrstak/net/msgstruct.hpp
Make sure we are using a steady clock. This pr can be tested by setting back the system time.
> Make sure we are using a steady clock

- README.md
> update check sums for version 2.2.0

- xmrstak/net/socket.cpp
> Clearer TLS error

- README.md
- xmrstak/cli/cli-miner.cpp
- xmrstak/config.tpl
- xmrstak/jconf.cpp
- xmrstak/params.hpp
Doc-only change. Includes 9201a7 so it should be merged after #701
> Link API documentation

- doc/compile_Windows.md
> Update compile_Windows.md - Minor Spelling error

- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
Remove branch divergences in AMD OpenCl code based on #454.
The effect of this PR should be a very small hash rate increase.
difference to #454
- Instead of using the OpenCl select statement I used short if which should be translated to the equal code. 
- this PR is not using unsave casts to `uint` for pointer
@JoKeRz42o @JerichoJones could you please test this PR?
> remove branch differgence in OpenCL code

- doc/FAQ.md
I removed typos, changed the wording and made the whole thing more noob-friendly. Probably going to update the other parts of the FAQ, too if I find the time.
> Improved SeLockMemoryPrivilege part in FAQ

- README.md
> change psychocrypt's donation address

- xmrstak/misc/uac.cpp
remove warning `#pragma once in main file`
> remove warning

- xmrstak/backend/amd/config.tpl
- xmrstak/backend/cpu/config.tpl
- xmrstak/backend/nvidia/config.tpl
This is my first time attempting to use github. I think I'm trying to commit to the dev branch but I am not knowledgeable enough to be certain. Sorry if it's wrong.
> Updated config.tpl comments to include how to exclude CPU/GPUs

- xmrstak/backend/amd/autoAdjust.hpp
Add missing VEGA names for current and up coming AMD VEGA GPUs
> update VEGA names for auto suggestion

- doc/compile_Windows.md
There are a lot of hiccups on this step that catch many noobs in the AEON Slack Channel. Caught me when I first tried compiling as well. 
> Simplified compile instructions for noobs

- doc/compile_Windows.md
CUDA/Develpment  -> CUDA/Development
> Fixed Minor Typo

- xmrstak/backend/amd/autoAdjust.hpp
increase the intensity limit for AEON
> improve AMD auto suggestion for AEON

- doc/compile_Windows.md
Added/Rewrote/Clarified instructions on how to compile in Windows; Fixed some typos and syntax; Added build option section.
> Update compile process (Windows)

- xmrstak/cli/cli-miner.cpp
- xmrstak/config.tpl
- xmrstak/jconf.cpp
- xmrstak/jconf.hpp
- xmrstak/misc/executor.cpp
- xmrstak/net/jpsock.cpp
- xmrstak/net/jpsock.hpp
- xmrstak/params.hpp
Tested on snipa's pool, minergate and nanopool.
> Add rig identifier

- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
- allow usage of Mesa OpenCl
Select Mesa OpenCL only if there is no AMD OpenCl available
> add Mesa OpenCL support

- xmrstak/backend/cpu/config.tpl
I was parsing some configs with grep and noticed that this line was missing its "*"
> Comment cleanup

- xmrstak/http/webdesign.cpp
Ref: https://github.com/fireice-uk/xmr-stak/pull/1146
Reopened a new PR since GitHub logged my squash as 4 commits instead...
> Fix #1122 - HTML report violates XML rules

- .gitignore
- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
This PR includes #1194 and extent the input buffer on the device too.
> Fix input buffer size cuda

- xmrstak/version.cpp
increase version for the next release
> increase version to 2.3.0

- xmrstak/backend/amd/amd_gpu/gpu.cpp
change warning when precompiled OpenCL code is not found
> OpenCL precompiled code message

- xmrstak/cli/cli-miner.cpp
> move option currency down

- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
revert #1198, the block size is limited to 84byte
> revert input size change

- doc/FAQ.md
- xmrstak/jconf.cpp
- xmrstak/pools.tpl
fix #1202
- update documentation
> rename `monero2` to `monero7`

- README.md
> Change video guide to a placeholder link

- README.md
the signatures for the next release will be in the release note itself
> remove old release signatures

- xmrstak/backend/amd/jconf.cpp
- xmrstak/backend/cpu/jconf.cpp
- xmrstak/backend/nvidia/jconf.cpp
> Add filename to backend errors

- doc/compile_Linux.md
Adding additional instructions for Linux distributions with new gcc compilers.
> instructions for new gcc versions

- doc/compile.md
- extract documentation fixes from #1141
- fix `compile.md`
> fix minor text issues in compile.md

- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/minethd.cpp
- xmrstak/backend/cpu/minethd.cpp
- xmrstak/backend/cpu/minethd.hpp
- xmrstak/backend/nvidia/minethd.cpp
- xmrstak/backend/nvidia/nvcc_code/cryptonight.hpp
- xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
- xmrstak/jconf.cpp
- xmrstak/jconf.hpp
close #1241
- add stellite coin
- refactor mining algo selection  …
- add `fork_height` to currency
- refactor algorithm selection
~~A test against a testnet pool was not possible because I have currently no test net address.~~
> add stellite coin

- xmrstak/version.cpp
> increase version for release to 2.4.0

- README.md
- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/version.cpp
- fix sumokoin bug introduced with 2.4.0
> Bug fix release 2.4.1

- README.md
- xmrstak/jconf.cpp
- xmrstak/pools.tpl
Haven just hardforked to cryptonight heavy and needs miner support.
> Add support for Haven (XHV) using CryptoNight Heavy

- xmrstak/backend/amd/amd_gpu/gpu.cpp
Fix spelling mistake in gpu.cpp
> Fix spelling mistake in gpu.cpp

- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/amd_gpu/gpu.hpp
- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
- xmrstak/backend/amd/autoAdjust.hpp
- xmrstak/backend/amd/minethd.cpp
- xmrstak/backend/cpu/autoAdjust.hpp
- xmrstak/backend/cpu/autoAdjustHwloc.hpp
- xmrstak/backend/cpu/crypto/cryptonight_common.cpp
- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
Use the maximum scratchpad size from before and after the fork.
After this PR it is possible to describe forks from a large scratchpad to a smaller without adding a transition algorithm. 
this PR includes #1372
> refactor scratchpad creation

- README.md
- xmrstak/jconf.cpp
- xmrstak/pools.tpl
Followup of #1426, I accidentally closed the branch by pushing to the branch of randing89.
@fireice-uk Could you please merge it, my plan was to merge the original PR but I did something wrong :-)
> BBSCoin support and get ready for cryptonight v7 upgrade

- xmrstak/version.cpp
version increase for the release 2.4.3
> version update to 2.4.3

- xmrstak/net/jpsock.cpp
> Small typo correction

- README.md
- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
- xmrstak/backend/cpu/crypto/cryptonight_aesni.h
- xmrstak/backend/cpu/minethd.cpp
- xmrstak/backend/cryptonight.hpp
- xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
- xmrstak/jconf.cpp
- xmrstak/misc/executor.cpp
- xmrstak/net/jpsock.cpp
solve #1494
- add algorithm `cryptonight_v7_stellite` (internal named: `cryptonight_stellite`)
> support stellite v4 fork

- xmrstak/net/jpsock.cpp
Some pools or proxys are sending multiple times in row the same job to the miner.
This PR will extent the miner to trigger an socket error if a job with the same `jobID` than the current active job is received.
Move motd evaluation before the possibility part where a job is ignored.
> ignore duplicated equal job from pools

- CMakeLists.txt
- doc/compile_Windows.md
Tested myself on Ubuntu 16.x and Windows 7
> Update for CUDA 9.2 Toolkit

- xmrstak/version.cpp
> increase version to 2.4.5

- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
- explicit loop unrolling
based on changes in @imperdin fork https://github.com/imperdin/xmr-stak/blob/master/xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
> optimize cn-heavy AMD

- README.md
- xmrstak/jconf.cpp
- xmrstak/pools.tpl
- remove all cryptonight coins (algorithm cryptonight can still be used)
- update README.md
> remove cryptonight coins

- xmrstak/version.cpp
increase version for the next release
> increase version to 2.4.6

- xmrstak/donate-level.hpp
Improve the grammar of the Dev donation setting.
> Incorrect Grammar fix

- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
Maybe this can make it into todays release? Simple output changes that tell us more about CUDA during runtime detection.  I've been running it on my rigs (on top of latest dev) for months, it's nice to have the details whilst also not being too verbose.
> Add detail to CUDA detections, better for issue reports

- xmrstak/backend/nvidia/nvcc_code/cuda_fast_int_math_v2.hpp
> NVIDIA: sqrt optimization cryptonight_v8

- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/amd_gpu/opencl/fast_int_math_v2.cl
- remove unused host function (relict from old refactoring)
- remove unused OpenCL full div function
> AMD: remove unused functions

- xmrstak/backend/cpu/autoAdjustHwloc.hpp
- xmrstak/backend/nvidia/minethd.cpp
- xmrstak/http/httpd.cpp
- xmrstak/http/webdesign.cpp
- xmrstak/http/webdesign.hpp
- xmrstak/pools.tpl
minor fixups for upcoming release
> spelling+typo touch-ups

- README.md
- xmrstak/cli/cli-miner.cpp
> Add Ryo sponsorship message

- xmrstak/version.cpp
version update for the next release
> update version to 2.5.0

- doc/compile_Linux.md
- doc/compile_Windows.md
- remove link to the AMD APP SDK from a share hoster
- update windows/linux documentation
> update AMD install docu

- xmrstak/backend/amd/amd_gpu/gpu.cpp
Remove a small bit of unused code in amd_gpu/gpu.cpp
> Remove dead code

- xmrstak/misc/executor.cpp
Co-authored-by: Hans Kristian Rosbach <hk-git@circlestorm.org>
> Add console warning on GPU error.

- xmrstak/version.cpp
version increase for the next release
> update version to 2.5.2

- xmrstak/version.cpp
> version increase to 2.6.0

- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
- xmrstak/backend/amd/amd_gpu/opencl/fast_div_heavy.cl
- xmrstak/backend/amd/amd_gpu/opencl/fast_int_math_v2.cl
Import optimizations from @SChernykh 
Optimize OpenCl ￼…
- optimize kernel cn0 and cn2
- optimize vast int math
- use more 32bit variables
> Topic amd refactoring

- xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
- xmrstak/backend/nvidia/nvcc_code/cuda_fast_div_heavy.hpp
port OpenCl optimized division to CUDA
Co-authored-by: SChernykh <sergey.v.chernykh@gmail.com>
> CUDA: optimize cn-heavy div

- xmrstak/backend/nvidia/nvcc_code/cuda_fast_int_math_v2.hpp
port optimizations from OpenCL.
Co-authored-by: SChernykh <sergey.v.chernykh@gmail.com>
> CUDA: optimize cn-v8 div

- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
- xmrstak/backend/amd/amd_gpu/opencl/wolf-aes.cl
Reduce local memory foot print to increase the occupancy.
Co-authored-by: SChernykh <sergey.v.chernykh@gmail.com>
> OpenCL: reduce local mem footprint

- xmrstak/version.cpp
> increase version to 2.7.0

- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
- xmrstak/backend/amd/amd_gpu/opencl/wolf-aes.cl
Since #2080 bittube2 is broken.
- reintroduce special AES function for bittube2
> fix bittube2

- doc/compile_Windows.md
update documentation and link AMD OCL-SDK light
> remove APP SDK with OCL SDK light

- xmrstak/version.cpp
> version increase to 2.7.1

- xmrstak/http/webdesign.cpp
- xmrstak/misc/executor.cpp
- xmrstak/net/jpsock.hpp
> (web) Add Rig ID to connection status web (and cli)

- xmrstak/http/webdesign.cpp
- xmrstak/misc/executor.cpp
> (web) Add currency to results report web (and cli)

- xmrstak/backend/nvidia/nvcc_code/cuda_cryptonight_gpu.hpp
- fix race condition during shared memory access
- optimize memory access
> fix cuda 10

- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
optimize the algorithm for cryptonight_gpu autosuggestion
> CUDA: optimze cn_gpu auto suggestion

- xmrstak/version.cpp
> update version to 2.8.0

- xmrstak/backend/amd/amd_gpu/opencl/cryptonight_gpu.cl
If comp_mode is used the code will not compile.
- fix compile issue
- fix wrong conditions to handle `comp_mode`
> OpencL: fix cn_gpu

- xmrstak/backend/amd/amd_gpu/gpu.cpp
OpenCl kernel using a larger work group size than configured by the
user to increase the occupancy. Depending on the algorithm and device
the size is limited.
This PR fixes that the user was able to select a invalid work group size.
> OpenCL: fix invalid work group size

- xmrstak/backend/amd/amd_gpu/opencl/cryptonight_gpu.cl
- xmrstak/backend/amd/autoAdjust.hpp
- use the user defined unroll
- auto suggestion:
- only tune for cn_gpu if this is the main user
currency (after a fork)
- set unroll to 1 for cn_gpu
> OpenCl: use user defined unroll in cn_gpu

- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
based on the suggestion from @xmrig https://github.com/xmrig/xmrig-amd/commit/db4e169f3a78f273abf89ea8cf5bba7eccf1490b
This PR replace #2216
> fix groestl, skein and blake

- xmrstak/backend/amd/amd_gpu/opencl/cryptonight_gpu.cl
Optimize cn_gpu (use more scalare values)
> OpenCL: optimize cn_gpu

- README.md
- xmrstak/backend/cryptonight.hpp
- xmrstak/jconf.cpp
- add cryptonight_v8_half
- re-add stellite and masari to the supported coins
> add cryptonight_v8_half

- README.md
- xmrstak/backend/cryptonight.hpp
- xmrstak/jconf.cpp
This PR replaces #2196 and add support for zelerius.
>  add Zelerius coin

- xmrstak/backend/amd/amd_gpu/opencl/cryptonight_gpu.cl
- xmrstak/backend/nvidia/nvcc_code/cuda_cryptonight_gpu.hpp
- rename variable names like `b` and `bb` to something with a little bit
of meaning.
> better variable nameining

- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
Optimize the auto adjustment for cn_gpu based on precomputed occupancy
values from CUDA10.
> CUDA: update cn_gpu auto adjust values

- README.md
- xmrstak/pools.tpl
- add more information if a algorithm derives from an other
- update `pools.tpl`
> update algorithm documentation

- xmrstak/backend/amd/amd_gpu/opencl/cryptonight_gpu.cl
#2229 was not solving the issues
- revert #2229
- introduce the working fix
> OpenCL: fix the fix for the blockchain driver

- xmrstak/version.cpp
update version for the next release
> increase version to 2.8.3

- xmrstak/version.cpp
> update version to 2.9.0

- xmrstak/backend/cpu/crypto/cryptonight_aesni.h
> fix wrong logic operator usage

- xmrstak/misc/executor.cpp
> dev pool change

- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
Fix again issues with vega and vii with the latest windows driver.
> OpenCL: fix windows vega and vii

- xmrstak/backend/cpu/crypto/CryptonightR_gen.cpp
- xmrstak/backend/cpu/crypto/cryptonight.h
- xmrstak/backend/cpu/crypto/cryptonight_aesni.h
- xmrstak/backend/cpu/minethd.cpp
add support for cnR double thread assembler
> use double hash for cryptonight_r

- xmrstak/backend/amd/OclCryptonightR_gen.cpp
- xmrstak/backend/amd/OclCryptonightR_gen.hpp
- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/backend/nvidia/CudaCryptonightR_gen.cpp
- xmrstak/backend/nvidia/CudaCryptonightR_gen.hpp
- xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
The original implementation of the cache release and create always new
kernel, this can lead into performance issues and my crashes.
> fix opencl and cuda cryptonight_r caching

- doc/usage.md
Remove a warning about unsupported CUDA from an older release.
> remove wrong documentation

- xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
- xmrstak/backend/amd/amd_gpu/opencl/wolf-aes.cl
Add support for non media ops for cryptonight_r
> cryptonight_r without mediaops

- xmrstak/backend/amd/amd_gpu/gpu.cpp
- xmrstak/cli/cli-miner.cpp
- xmrstak/misc/home_dir.hpp
- xmrstak/params.hpp
add option to control where the amd cache data should be stored
e.g.
`./xmr-stak -C supportxmr.txt --amdCacheDir $HOME/xxx`
> add cli option `amdCacheDir`

- xmrstak/version.cpp
> update version to 2.10.3

- .github/ISSUE_TEMPLATE/execution_bug_report.md
> fix execution issue template

- .github/ISSUE_TEMPLATE/execution_bug_report.md
- xmrstak/version.cpp
> port issue template fix

- xmrstak/jconf.cpp
> change lethean POW to cn_r

- xmrstak/jconf.cpp
pool.usxmrpool.com is not available anymore so we change the suggestion
> change xmr pool suggestion

- xmrstak/pools.tpl
I missed to rename the coin in the pools.tpl file
> rename intense to lethean

- xmrstak/jconf.cpp
- xmrstak/pools.tpl
The coin freehaven switched to pow cuckoo (not supported)
> remove freehaven support

- xmrstak/version.cpp
> increase version to 2.10.6

- README.md
Make clear the architecture at start of README.md to avoid confusion, even if indicated at Features later
https://github.com/fireice-uk/xmr-stak/issues/2427
> Make explicit the architecture of the project at beginning

- doc/usage.md
Nothing fancy just updated the broken links at the top of usage.md doc file.
> Updated the broken links in usage.md

- xmrstak/misc/executor.cpp
> fix used `empty()` instead of `clear()`

- .appveyor.yml
- .travis.yml
- update to cuda9 (required for xmr-stak-rx)
> [RX] fix CI

- README.md
- xmrstak/jconf.cpp
Aeon is forking on  25.10.1029 to a fpga minable POW.
> remove aeon support

- xmrstak/jconf.cpp
- xmrstak/pools.tpl
Add `monero`, `loki` and `wownero` as currencies.
> [RX] add currency names

- .appveyor.yml
- .travis.yml
- xmrstak/backend/cpu/crypto/cryptonight_aesni.h
- xmrstak/backend/cpu/hwlocMemory.cpp
- xmrstak/backend/cpu/minethd.cpp
- xmrstak/backend/cpu/minethd.hpp
- xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
- xmrstak/cli/cli-miner.cpp
- xmrstak/jconf.cpp
- xmrstak/misc/executor.cpp
- xmrstak/net/socket.cpp
- xmrstak/pools.tpl
- xmrstak/version.cpp
- Correct authors of RandomX mining code #2551
- fix hwloc warning #2556
- fix ignored tls on first start #2558
- fix miner benchmark mode #2561
- NVIDIA: fix auto adjustment #2567
> xmr-stak-rx 1.0.1 release

- xmrstak/jconf.cpp
- xmrstak/pools.tpl
Monero is now supported via xmr-stak-rx
> remove monero support

- xmrstak/backend/cpu/crypto/randomx/aes_hash.cpp
- xmrstak/backend/cpu/crypto/randomx/aes_hash.hpp
- xmrstak/backend/cpu/crypto/randomx/intrin_portable.h
- xmrstak/backend/cpu/crypto/randomx/jit_compiler.hpp
- xmrstak/backend/cpu/crypto/randomx/jit_compiler_x86.cpp
- xmrstak/backend/cpu/crypto/randomx/jit_compiler_x86.hpp
- xmrstak/backend/cpu/crypto/randomx/randomx.cpp
- xmrstak/backend/cpu/crypto/randomx/randomx.h
- xmrstak/backend/cpu/crypto/randomx/virtual_machine.cpp
- xmrstak/backend/cpu/crypto/randomx/virtual_machine.hpp
- xmrstak/backend/cpu/minethd.cpp
- merge xmrig 5.1.0 changes
- Only update the hash statistics 2-5 times per second
> [RX] optimize randomX

- xmrstak/backend/cpu/autoAdjust.hpp
- xmrstak/backend/cpu/autoAdjustHwloc.hpp
Remove unsued parameters from cpu.txt
> [RX] CPU: remove unused params

- xmrstak/backend/cpu/minethd.cpp
- reduce the number of lookups if the job has changed
This optimization stabilze the hashrate and give 0.5% better results.
> optimize hash rate
